SET FOREIGN_KEY_CHECKS=1;

use test;
CREATE TABLE LIFECYCLE_VERSION (
  TYPE VARCHAR(10) NOT NULL PRIMARY KEY,
  UUID VARCHAR(100) NOT NULL,
  UPDATED_ON TIMESTAMP  NULL) ENGINE=InnoDB;;

CREATE TABLE LIFECYCLE_RUNTIME(
  NAME VARCHAR(100) NOT NULL PRIMARY KEY,
  TYPE VARCHAR(40) NOT NULL,
  HOSTNAME VARCHAR(250),
  PORT VARCHAR(10),
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL ) ENGINE=InnoDB;

CREATE TABLE LIFECYCLE_RUNTIME_PROPERTY(
  NAME VARCHAR(100) NOT NULL,
  PROPERTYNAME VARCHAR(100) NOT NULL,
  PROPERTYVALUE VARCHAR(250),
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT LIFECYCLE_RUNTIME_pk PRIMARY KEY (NAME, PROPERTYNAME),
  CONSTRAINT runtimepp_fkey FOREIGN KEY (NAME) REFERENCES LIFECYCLE_RUNTIME(NAME)) ENGINE=InnoDB;


CREATE TABLE LIFECYCLE_PARTITION(
  ID VARCHAR(100) NOT NULL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  RUNTIME_NAME VARCHAR(100) NOT NULL,
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT partitions_fkey FOREIGN KEY (RUNTIME_NAME) REFERENCES LIFECYCLE_RUNTIME(NAME)) ENGINE=InnoDB;

CREATE TABLE LIFECYCLE_PARTITION_PROPERTY(
  ID  VARCHAR(100) NOT NULL,
  PROPERTYNAME VARCHAR(100) NOT NULL,
  PROPERTYVALUE VARCHAR(250),
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT LIFECYCLE_PP_pk PRIMARY KEY (ID, PROPERTYNAME),
  CONSTRAINT partitionpp_fkey FOREIGN KEY (ID) REFERENCES LIFECYCLE_PARTITION(ID)) ENGINE=InnoDB;

CREATE TABLE LIFECYCLE_ENVIRONMENT(
  NAME VARCHAR(40) NOT NULL PRIMARY KEY,
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL ) ENGINE=InnoDB;

CREATE TABLE LIFECYCLE_PARTITION_REF(
  ENVIRONMENT_NAME VARCHAR(40) NOT NULL,
  ID VARCHAR(100) NOT NULL,
  RUNTIME_REF VARCHAR(100) NOT NULL,
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT partition_ref_env_fkey FOREIGN KEY (ENVIRONMENT_NAME) REFERENCES LIFECYCLE_ENVIRONMENT(NAME),
  CONSTRAINT partition_ref_fkey FOREIGN KEY (ID) REFERENCES LIFECYCLE_PARTITION(ID),
  CONSTRAINT partition_ref_runtime_fkey FOREIGN KEY (RUNTIME_REF) REFERENCES LIFECYCLE_RUNTIME(NAME),
  CONSTRAINT LIFECYCLE_PR_pk PRIMARY KEY (ENVIRONMENT_NAME, ID)) ENGINE=InnoDB;

CREATE TABLE LIFECYCLE_TENANT(
  ID VARCHAR(100) NOT NULL PRIMARY KEY,
  NAME VARCHAR (100),
  TOP_LEVEL_DIR VARCHAR (250),
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL) ENGINE=InnoDB;


CREATE TABLE LIFECYCLE_SERVICE(
  ID VARCHAR(100) NOT NULL PRIMARY KEY,
  SERVICE_TYPE VARCHAR(100) NOT NULL,
  NAME VARCHAR(100),
  ENVIRONMENT_REF VARCHAR(40),
  TENANT_ID VARCHAR(100) NOT NULL,
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT SERVICE_ENVIRONMENT_FKEY FOREIGN KEY (ENVIRONMENT_REF) REFERENCES LIFECYCLE_ENVIRONMENT(NAME),
  CONSTRAINT SERVICE_TENANT_FKEY FOREIGN KEY (TENANT_ID) REFERENCES LIFECYCLE_TENANT(ID)) ENGINE=InnoDB;

CREATE TABLE LIFECYCLE_PDB(
  ID VARCHAR(100) NOT NULL PRIMARY KEY,
  NAME VARCHAR(100),
  STATUS VARCHAR(40),
  SERVICE_ID VARCHAR(100),
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT PDB_SERVICE_FKEY FOREIGN KEY (SERVICE_ID) REFERENCES LIFECYCLE_SERVICE(ID)) ENGINE=InnoDB;

CREATE TABLE LIFECYCLE_ASSOCIATION(
  PARTITION1 VARCHAR(100) NOT NULL PRIMARY KEY,
  PARTITION2 VARCHAR(100) NOT NULL,
  ENVIRONMENT_NAME VARCHAR(40),
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT ASSOC_ENV_FKEY FOREIGN KEY (ENVIRONMENT_NAME) REFERENCES LIFECYCLE_ENVIRONMENT(NAME),
  CONSTRAINT ASSOC1_FKEY FOREIGN KEY (PARTITION1) REFERENCES LIFECYCLE_PARTITION(ID),
  CONSTRAINT ASSOC2_FKEY FOREIGN KEY (PARTITION2) REFERENCES LIFECYCLE_PARTITION(ID)) ENGINE=InnoDB;


CREATE TABLE LIFECYCLE_SERVICE_RESOURCE(
  NAME VARCHAR(100) NOT NULL,
  TYPE VARCHAR(40) NOT NULL,
  SERVICE_ID VARCHAR(40) NOT NULL,
  TENANT_ID VARCHAR(100) NOT NULL,
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT RES_SERV_FKEY1 FOREIGN KEY (SERVICE_ID) REFERENCES LIFECYCLE_SERVICE(ID),
  CONSTRAINT RES_SERV_FKEY2 FOREIGN KEY (TENANT_ID) REFERENCES LIFECYCLE_SERVICE(TENANT_ID),
  CONSTRAINT LIFECYCLE_SR_pk PRIMARY KEY(NAME, SERVICE_ID, TENANT_ID)) ENGINE=InnoDB;

CREATE TABLE LIFECYCLE_TENANT_RESOURCE(
  NAME VARCHAR(100) NOT NULL PRIMARY KEY,
  TYPE VARCHAR(40) NOT NULL,
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL) ENGINE=InnoDB;

CREATE TABLE LIFECYCLE_SRESOURCE_PROPERTY(
  SERVICE_ID VARCHAR(40) NOT NULL,
  RESOURCE_NAME VARCHAR(100) NOT NULL,
  TENANT_ID VARCHAR(100),
  PROPERTYNAME VARCHAR(100) NOT NULL,
  PROPERTYVALUE VARCHAR(250),
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT LIFECYCLE_SRPP_fk FOREIGN KEY (SERVICE_ID, RESOURCE_NAME, TENANT_ID)
    REFERENCES LIFECYCLE_SERVICE_RESOURCE(SERVICE_ID, NAME, TENANT_ID),
  CONSTRAINT LIFECYCLE_SRPP_pk PRIMARY KEY (SERVICE_ID, RESOURCE_NAME, TENANT_ID, PROPERTYNAME)) ENGINE=InnoDB;


CREATE TABLE LIFECYCLE_TRESOURCE_PROPERTY(
  NAME VARCHAR(100) NOT NULL,
  PROPERTYNAME VARCHAR(100) NOT NULL,
  PROPERTYVALUE VARCHAR(250),
  CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_ON TIMESTAMP NULL,
  CONSTRAINT LIFECYCLE_TRPP_pk PRIMARY KEY (NAME, PROPERTYNAME),
  CONSTRAINT LIFECYCLE_TRPP_fk FOREIGN KEY (NAME) REFERENCES LIFECYCLE_TENANT_RESOURCE(NAME)) ENGINE=InnoDB;
