package org.python.tests;

public interface VisibilityResults {
   int UNUSED = -1;
   int PROTECTED_STATIC_FIELD = 1;
   int PROTECTED_FIELD = 2;
   int PACKAGE_STATIC_FIELD = 3;
   int PACKAGE_FIELD = 4;
   int PROTECTED_STATIC_METHOD = 5;
   int OVERLOADED_STATIC_METHOD = 6;
   int PROTECTED_METHOD = 7;
   int OVERLOADED_PROTECTED_METHOD = 8;
   int PACKAGE_STATIC_METHOD = 9;
   int PACKAGE_METHOD = 10;
   int PUBLIC_FIELD = 101;
   int PUBLIC_STATIC_FIELD = 102;
   int PUBLIC_METHOD = 103;
   int OVERLOADED_PUBLIC_METHOD = 104;
   int EXTRA_ARG_PUBLIC_METHOD = 105;
   int OVERLOADED_EXTRA_ARG_PUBLIC_METHOD = 106;
   int PUBLIC_STATIC_METHOD = 107;
   int OVERLOADED_PUBLIC_STATIC_METHOD = 108;
   int EXTRA_ARG_PUBLIC_STATIC_METHOD = 109;
   int PUBLIC_METHOD_FIELD = 110;
   int PUBLIC_STATIC_METHOD_FIELD = 111;
   int VISIBLE_SHARED_NAME_FIELD = 112;
   int SUBCLASS_OVERRIDE = 201;
   int SUBCLASS_OVERLOAD = 202;
   int SUBCLASS_STATIC_OVERRIDE = 203;
   int SUBCLASS_STATIC_OVERLOAD = 204;
   int SUBVISIBLE_SHARED_NAME_FIELD = 205;
}
