package weblogic.xml.schema.binding.internal;

import weblogic.xml.schema.binding.util.StdNamespace;
import weblogic.xml.stream.ElementFactory;
import weblogic.xml.stream.XMLName;

public final class SoapTypes {
   public static final String HREF = "href";
   public static final String ID = "id";
   public static final XMLName HREF_NAME = ElementFactory.createXMLName("href");
   public static final XMLName ID_NAME = ElementFactory.createXMLName("id");
   public static final String ENCODING_URI = StdNamespace.instance().soapEncoding();
   public static final String WSDL_URI = StdNamespace.instance().wsdl();
   public static final XMLName Array;
   public static final XMLName WsdlArrayType;
   public static final XMLName SoapArrayType;
   public static final XMLName SOAP_BASE64_ENAME;
   public static final XMLName SOAP_ANYURI_ENAME;
   public static final XMLName SOAP_BASE64BINARY_ENAME;
   public static final XMLName SOAP_BOOLEAN_ENAME;
   public static final XMLName SOAP_DATETIME_ENAME;
   public static final XMLName SOAP_DATE_ENAME;
   public static final XMLName SOAP_DECIMAL_ENAME;
   public static final XMLName SOAP_DOUBLE_ENAME;
   public static final XMLName SOAP_DURATION_ENAME;
   public static final XMLName SOAP_FLOAT_ENAME;
   public static final XMLName SOAP_GDAY_ENAME;
   public static final XMLName SOAP_GMONTHDAY_ENAME;
   public static final XMLName SOAP_GMONTH_ENAME;
   public static final XMLName SOAP_GYEARMONTH_ENAME;
   public static final XMLName SOAP_GYEAR_ENAME;
   public static final XMLName SOAP_HEXBINARY_ENAME;
   public static final XMLName SOAP_NOTATION_ENAME;
   public static final XMLName SOAP_QNAME_ENAME;
   public static final XMLName SOAP_STRING_ENAME;
   public static final XMLName SOAP_TIME_ENAME;
   public static final XMLName SOAP_NORMALIZED_STRING_ENAME;
   public static final XMLName SOAP_TOKEN_ENAME;
   public static final XMLName SOAP_LANGUAGE_ENAME;
   public static final XMLName SOAP_NMTOKEN_ENAME;
   public static final XMLName SOAP_NMTOKENS_ENAME;
   public static final XMLName SOAP_NAME_ENAME;
   public static final XMLName SOAP_NCNAME_ENAME;
   public static final XMLName SOAP_ID_ENAME;
   public static final XMLName SOAP_IDREF_ENAME;
   public static final XMLName SOAP_IDREFS_ENAME;
   public static final XMLName SOAP_ENTITY_ENAME;
   public static final XMLName SOAP_ENTITIES_ENAME;
   public static final XMLName SOAP_INTEGER_ENAME;
   public static final XMLName SOAP_NONPOSITIVEINTEGER_ENAME;
   public static final XMLName SOAP_NEGATIVEINTEGER_ENAME;
   public static final XMLName SOAP_LONG_ENAME;
   public static final XMLName SOAP_INT_ENAME;
   public static final XMLName SOAP_SHORT_ENAME;
   public static final XMLName SOAP_BYTE_ENAME;
   public static final XMLName SOAP_NONNEGATIVEINTEGER_ENAME;
   public static final XMLName SOAP_UNSIGNEDLONG_ENAME;
   public static final XMLName SOAP_UNSIGNEDINT_ENAME;
   public static final XMLName SOAP_UNSIGNEDSHORT_ENAME;
   public static final XMLName SOAP_UNSIGNEDBYTE_ENAME;
   public static final XMLName SOAP_POSITIVEINTEGER_ENAME;

   static {
      Array = ElementFactory.createXMLName(ENCODING_URI, "Array");
      WsdlArrayType = ElementFactory.createXMLName(WSDL_URI, "arrayType");
      SoapArrayType = ElementFactory.createXMLName(ENCODING_URI, "arrayType");
      SOAP_BASE64_ENAME = ElementFactory.createXMLName(ENCODING_URI, "base64");
      SOAP_ANYURI_ENAME = ElementFactory.createXMLName(ENCODING_URI, "anyURI");
      SOAP_BASE64BINARY_ENAME = ElementFactory.createXMLName(ENCODING_URI, "base64Binary");
      SOAP_BOOLEAN_ENAME = ElementFactory.createXMLName(ENCODING_URI, "boolean");
      SOAP_DATETIME_ENAME = ElementFactory.createXMLName(ENCODING_URI, "dateTime");
      SOAP_DATE_ENAME = ElementFactory.createXMLName(ENCODING_URI, "date");
      SOAP_DECIMAL_ENAME = ElementFactory.createXMLName(ENCODING_URI, "decimal");
      SOAP_DOUBLE_ENAME = ElementFactory.createXMLName(ENCODING_URI, "double");
      SOAP_DURATION_ENAME = ElementFactory.createXMLName(ENCODING_URI, "duration");
      SOAP_FLOAT_ENAME = ElementFactory.createXMLName(ENCODING_URI, "float");
      SOAP_GDAY_ENAME = ElementFactory.createXMLName(ENCODING_URI, "gDay");
      SOAP_GMONTHDAY_ENAME = ElementFactory.createXMLName(ENCODING_URI, "gMonthDay");
      SOAP_GMONTH_ENAME = ElementFactory.createXMLName(ENCODING_URI, "gMonth");
      SOAP_GYEARMONTH_ENAME = ElementFactory.createXMLName(ENCODING_URI, "gYearMonth");
      SOAP_GYEAR_ENAME = ElementFactory.createXMLName(ENCODING_URI, "gYear");
      SOAP_HEXBINARY_ENAME = ElementFactory.createXMLName(ENCODING_URI, "hexBinary");
      SOAP_NOTATION_ENAME = ElementFactory.createXMLName(ENCODING_URI, "NOTATION");
      SOAP_QNAME_ENAME = ElementFactory.createXMLName(ENCODING_URI, "QName");
      SOAP_STRING_ENAME = ElementFactory.createXMLName(ENCODING_URI, "string");
      SOAP_TIME_ENAME = ElementFactory.createXMLName(ENCODING_URI, "time");
      SOAP_NORMALIZED_STRING_ENAME = ElementFactory.createXMLName(ENCODING_URI, "normalizedString");
      SOAP_TOKEN_ENAME = ElementFactory.createXMLName(ENCODING_URI, "token");
      SOAP_LANGUAGE_ENAME = ElementFactory.createXMLName(ENCODING_URI, "language");
      SOAP_NMTOKEN_ENAME = ElementFactory.createXMLName(ENCODING_URI, "NMTOKEN");
      SOAP_NMTOKENS_ENAME = ElementFactory.createXMLName(ENCODING_URI, "NMTOKENS");
      SOAP_NAME_ENAME = ElementFactory.createXMLName(ENCODING_URI, "Name");
      SOAP_NCNAME_ENAME = ElementFactory.createXMLName(ENCODING_URI, "NCName");
      SOAP_ID_ENAME = ElementFactory.createXMLName(ENCODING_URI, "ID");
      SOAP_IDREF_ENAME = ElementFactory.createXMLName(ENCODING_URI, "IDREF");
      SOAP_IDREFS_ENAME = ElementFactory.createXMLName(ENCODING_URI, "IDREFS");
      SOAP_ENTITY_ENAME = ElementFactory.createXMLName(ENCODING_URI, "ENTITY");
      SOAP_ENTITIES_ENAME = ElementFactory.createXMLName(ENCODING_URI, "ENTITIES");
      SOAP_INTEGER_ENAME = ElementFactory.createXMLName(ENCODING_URI, "integer");
      SOAP_NONPOSITIVEINTEGER_ENAME = ElementFactory.createXMLName(ENCODING_URI, "nonPositiveInteger");
      SOAP_NEGATIVEINTEGER_ENAME = ElementFactory.createXMLName(ENCODING_URI, "negativeInteger");
      SOAP_LONG_ENAME = ElementFactory.createXMLName(ENCODING_URI, "long");
      SOAP_INT_ENAME = ElementFactory.createXMLName(ENCODING_URI, "int");
      SOAP_SHORT_ENAME = ElementFactory.createXMLName(ENCODING_URI, "short");
      SOAP_BYTE_ENAME = ElementFactory.createXMLName(ENCODING_URI, "byte");
      SOAP_NONNEGATIVEINTEGER_ENAME = ElementFactory.createXMLName(ENCODING_URI, "nonNegativeInteger");
      SOAP_UNSIGNEDLONG_ENAME = ElementFactory.createXMLName(ENCODING_URI, "unsignedLong");
      SOAP_UNSIGNEDINT_ENAME = ElementFactory.createXMLName(ENCODING_URI, "unsignedInt");
      SOAP_UNSIGNEDSHORT_ENAME = ElementFactory.createXMLName(ENCODING_URI, "unsignedShort");
      SOAP_UNSIGNEDBYTE_ENAME = ElementFactory.createXMLName(ENCODING_URI, "unsignedByte");
      SOAP_POSITIVEINTEGER_ENAME = ElementFactory.createXMLName(ENCODING_URI, "positiveInteger");
   }
}
