package com.bea.security.saml2.util;

import com.bea.security.utils.saml2.SSOConstants;

public interface SAML2Constants extends SSOConstants {
   String SAML2_CONFORMATION_BEARER = "urn:oasis:names:tc:SAML:2.0:cm:bearer";
   String SAML2_CONFORMATION_SENDER_VOUCHES = "urn:oasis:names:tc:SAML:2.0:cm:sender-vouches";
   String SAML2_CONFORMATION_HOLDER_KEY = "urn:oasis:names:tc:SAML:2.0:cm:holder-of-key";
   String SAML2_ISSUER_FORMAT_ENTITY = "urn:oasis:names:tc:SAML:2.0:nameid-format:entity";
   String SAML2_WEBSSO_SP_PARTNER = "WEBSSOSPPARTNER";
   String SAML2_WEBSSO_IDP_PARTNER = "WEBSSOIDPPARTNER";
   String SAML2_WSS_SP_PARTNER = "WSSSPPARTNER";
   String SAML2_WSS_IDP_PARTNER = "WSSIDPPARTNER";
   String HTTP_REDIRECT = "HTTP/Redirect";
   String HTTP_POST = "HTTP/POST";
   String HTTP_ARTIFACT = "HTTP/Artifact";
   String SOAP_HTTP = "SOAP";
   String SOAP_HTTP_URN = "urn:oasis:names:tc:SAML:2.0:bindings:SOAP";
   String HTTP_ARTIFACT_URN = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact";
   String HTTP_POST_URN = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST";
   String HTTP_REDIRECT_URN = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect";
   String REDIRECT_URI = "/redirect";
   String POST_URI = "/post";
   String ARTIFACT_URI = "/artifact";
   String SOAP_URI = "/soap";
   String INITIATOR_URI = "/initiator";
   String LOGIN_RETURN_URI = "/login-return";
   String SSO_PATH = "sso";
   String ACS_PATH = "acs";
   String ARS_PATH = "ars";
   String IDP_SERVICE_PATH = "idp";
   String SP_SERVICE_PATH = "sp";
   String IDP_SSO_PATH = "/idp/sso";
   String IDP_SSO_ARTIFACT_PATH = "/idp/sso/artifact";
   String IDP_SSO_POST_PATH = "/idp/sso/post";
   String IDP_SSO_REDIRECT_PATH = "/idp/sso/redirect";
   String IDP_SSO_INITIATOR_PATH = "/idp/sso/initiator";
   String IDP_SSO_LOGIN_RETURN_PATH = "/idp/sso/login-return";
   String IDP_ARS_PATH = "/idp/ars/soap";
   String IDP_DEFAULT_LOGIN_PATH = "/idp/login";
   String SP_ACS_PATH = "/sp/acs";
   String SP_ACS_ARTIFACT_PATH = "/sp/acs/artifact";
   String SP_ACS_POST_PATH = "/sp/acs/post";
   String SP_SSO_INITIATOR_PATH = "/sp/sso/initiator";
   String SP_ARS_PATH = "/sp/ars/soap";
   String IDP_INITIATOR_END_URI = "/initiator";
   String IDP_LOGIN_RETURN_PATH = "/idp/sso/login-return";
   String DESTINATION_URL = "com.bea.security.saml2.destination";
   String RELAY_STATE_ATTR = "com.bea.security.saml2.relayState";
   String SAML_CONTENT = "com.bea.security.saml2.samlContent";
   String OPEN_SAML_LOGGER_NAME = "org.opensaml";
   String RSA_KEY_TYPE = "RSA";
   String DSA_KEY_TYPE = "DSA";
   String SIGNATUREMETHOD_RSA_SHA256_URI = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256";
   String SIGNATUREMETHOD_DSA_SHA256_URI = "http://www.w3.org/2009/xmldsig11#dsa-sha256";
   String SINGLE_PLUS_TARGET_MATCH = "target:+:";
   String SINGLE_MINUS_TARGET_MATCH = "target:-:";
   String WILDCARD_TARGET_MATCH = "target:*:";
   String LOGIN_IDENTITY_DATA_KEY = "weblogic.security.saml2.websso.assertion";
}
