package weblogic.j2ee.descriptor.wl;

import java.beans.BeanDescriptor;
import java.beans.PropertyDescriptor;
import java.beans.SimpleBeanInfo;
import java.util.ArrayList;
import java.util.List;

public class JspDescriptorBeanDConfigBeanInfo extends SimpleBeanInfo {
   BeanDescriptor bd = new BeanDescriptor(JspDescriptorBeanDConfig.class);
   static PropertyDescriptor[] pds = null;

   public BeanDescriptor getBeanDescriptor() {
      return this.bd;
   }

   public PropertyDescriptor[] getPropertyDescriptors() {
      if (pds != null) {
         return pds;
      } else {
         List plist = new ArrayList();

         try {
            PropertyDescriptor pd = new PropertyDescriptor("Keepgenerated", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isKeepgenerated", "setKeepgenerated");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("PackagePrefix", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getPackagePrefix", "setPackagePrefix");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("SuperClass", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getSuperClass", "setSuperClass");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("PageCheckSeconds", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getPageCheckSeconds", "setPageCheckSeconds");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("PageCheckSecondsSet", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isPageCheckSecondsSet", (String)null);
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("Precompile", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isPrecompile", "setPrecompile");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("PrecompileContinue", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isPrecompileContinue", "setPrecompileContinue");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("Verbose", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isVerbose", "setVerbose");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("WorkingDir", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getWorkingDir", "setWorkingDir");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("PrintNulls", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isPrintNulls", "setPrintNulls");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("BackwardCompatible", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isBackwardCompatible", "setBackwardCompatible");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("Encoding", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getEncoding", "setEncoding");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("ExactMapping", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isExactMapping", "setExactMapping");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("DefaultFileName", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getDefaultFileName", "setDefaultFileName");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("RtexprvalueJspParamName", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isRtexprvalueJspParamName", "setRtexprvalueJspParamName");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("Debug", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isDebug", "setDebug");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("Id", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getId", "setId");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("CompressHtmlTemplate", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isCompressHtmlTemplate", "setCompressHtmlTemplate");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("OptimizeJavaExpression", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isOptimizeJavaExpression", "setOptimizeJavaExpression");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("ResourceProviderClass", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getResourceProviderClass", "setResourceProviderClass");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("StrictStaleCheck", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isStrictStaleCheck", "setStrictStaleCheck");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("StrictJspDocumentValidation", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isStrictJspDocumentValidation", "setStrictJspDocumentValidation");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("ExpressionInterceptor", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getExpressionInterceptor", "setExpressionInterceptor");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("EL22BackwardCompatible", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "isEL22BackwardCompatible", "setEL22BackwardCompatible");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("CompilerSourceVM", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getCompilerSourceVM", "setCompilerSourceVM");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("CompilerTargetVM", Class.forName("weblogic.j2ee.descriptor.wl.JspDescriptorBeanDConfig"), "getCompilerTargetVM", "setCompilerTargetVM");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pds = (PropertyDescriptor[])((PropertyDescriptor[])plist.toArray(new PropertyDescriptor[0]));
            return pds;
         } catch (Throwable var4) {
            var4.printStackTrace();
            throw new AssertionError("Failed to create PropertyDescriptors for JspDescriptorBeanDConfigBeanInfo");
         }
      }
   }
}
