package weblogic.j2ee.descriptor.wl;

import java.beans.BeanDescriptor;
import java.beans.PropertyDescriptor;
import java.beans.SimpleBeanInfo;
import java.util.ArrayList;
import java.util.List;

public class MessageDrivenDescriptorBeanDConfigBeanInfo extends SimpleBeanInfo {
   BeanDescriptor bd = new BeanDescriptor(MessageDrivenDescriptorBeanDConfig.class);
   static PropertyDescriptor[] pds = null;

   public BeanDescriptor getBeanDescriptor() {
      return this.bd;
   }

   public PropertyDescriptor[] getPropertyDescriptors() {
      if (pds != null) {
         return pds;
      } else {
         List plist = new ArrayList();

         try {
            PropertyDescriptor pd = new PropertyDescriptor("Pool", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getPool", (String)null);
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("PoolSet", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "isPoolSet", (String)null);
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("TimerDescriptor", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getTimerDescriptor", (String)null);
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("TimerDescriptorSet", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "isTimerDescriptorSet", (String)null);
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("ResourceAdapterJNDIName", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getResourceAdapterJNDIName", "setResourceAdapterJNDIName");
            pd.setValue("dependency", true);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("DestinationJNDIName", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getDestinationJNDIName", "setDestinationJNDIName");
            pd.setValue("dependency", true);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("InitialContextFactory", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getInitialContextFactory", "setInitialContextFactory");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("ProviderUrl", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getProviderUrl", "setProviderUrl");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("ConnectionFactoryJNDIName", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getConnectionFactoryJNDIName", "setConnectionFactoryJNDIName");
            pd.setValue("dependency", true);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("DestinationResourceLink", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getDestinationResourceLink", "setDestinationResourceLink");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("ConnectionFactoryResourceLink", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getConnectionFactoryResourceLink", "setConnectionFactoryResourceLink");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("JmsPollingIntervalSeconds", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getJmsPollingIntervalSeconds", "setJmsPollingIntervalSeconds");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("JmsClientId", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getJmsClientId", "setJmsClientId");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("GenerateUniqueJmsClientId", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "isGenerateUniqueJmsClientId", "setGenerateUniqueJmsClientId");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("DurableSubscriptionDeletion", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "isDurableSubscriptionDeletion", "setDurableSubscriptionDeletion");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("MaxMessagesInTransaction", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getMaxMessagesInTransaction", "setMaxMessagesInTransaction");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("DistributedDestinationConnection", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getDistributedDestinationConnection", "setDistributedDestinationConnection");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("Use81StylePolling", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "isUse81StylePolling", "setUse81StylePolling");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("InitSuspendSeconds", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getInitSuspendSeconds", "setInitSuspendSeconds");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("MaxSuspendSeconds", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getMaxSuspendSeconds", "setMaxSuspendSeconds");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", true);
            pd.setValue("key", false);
            pd.setValue("dynamic", true);
            plist.add(pd);
            pd = new PropertyDescriptor("SecurityPlugin", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getSecurityPlugin", (String)null);
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("SecurityPluginSet", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "isSecurityPluginSet", (String)null);
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pd = new PropertyDescriptor("Id", Class.forName("weblogic.j2ee.descriptor.wl.MessageDrivenDescriptorBeanDConfig"), "getId", "setId");
            pd.setValue("dependency", false);
            pd.setValue("declaration", false);
            pd.setValue("configurable", false);
            pd.setValue("key", false);
            pd.setValue("dynamic", false);
            plist.add(pd);
            pds = (PropertyDescriptor[])((PropertyDescriptor[])plist.toArray(new PropertyDescriptor[0]));
            return pds;
         } catch (Throwable var4) {
            var4.printStackTrace();
            throw new AssertionError("Failed to create PropertyDescriptors for MessageDrivenDescriptorBeanDConfigBeanInfo");
         }
      }
   }
}
