package weblogic.management.runtime;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import weblogic.utils.codegen.ImplementationFactory;
import weblogic.utils.codegen.RoleInfoImplementationFactory;

public class BeanInfoFactory implements RoleInfoImplementationFactory {
   private static final Map interfaceMap = new HashMap(266);
   private static final ArrayList roleInfoList;
   private static final BeanInfoFactory SINGLETON;

   public static final ImplementationFactory getInstance() {
      return SINGLETON;
   }

   public String getImplementationClassName(String interfaceName) {
      return (String)interfaceMap.get(interfaceName);
   }

   public String[] getInterfaces() {
      Set keySet = interfaceMap.keySet();
      return (String[])((String[])keySet.toArray(new String[keySet.size()]));
   }

   public String[] getInterfacesWithRoleInfo() {
      return (String[])((String[])roleInfoList.toArray(new String[roleInfoList.size()]));
   }

   public String getRoleInfoImplementationFactoryTimestamp() {
      try {
         InputStream is = this.getClass().getResourceAsStream("BeanInfoFactory.tstamp");
         return (new BufferedReader(new InputStreamReader(is))).readLine();
      } catch (IOException var2) {
         throw new RuntimeException(var2);
      }
   }

   static {
      interfaceMap.put("weblogic.management.runtime.AggregateProgressMBean", "weblogic.server.AggregateProgressMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.AppClientComponentRuntimeMBean", "weblogic.j2eeclient.AppClientComponentRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.AppDeploymentRuntimeMBean", "weblogic.management.deploy.internal.AppDeploymentRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.AppRuntimeStateRuntimeMBean", "weblogic.management.deploy.internal.AppRuntimeStateRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ApplicationRuntimeMBean", "weblogic.application.internal.ApplicationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.AsyncReplicationRuntimeMBean", "weblogic.cluster.replication.AsyncReplicationRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.AuthenticatorRuntimeMBean", "weblogic.security.AuthenticatorRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.BatchJobRepositoryRuntimeMBean", "com.oracle.batch.connector.impl.BatchJobRepositoryRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.CacheMonitorRuntimeMBean", "weblogic.cache.management.CacheMonitorRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.CapacityRuntimeMBean", "weblogic.work.CapacityRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ChannelRuntimeMBean", "weblogic.servlet.httppubsub.runtime.ChannelRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ClassLoaderRuntimeMBean", "weblogic.t3.srvr.ClassLoaderRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ClusterRuntimeMBean", "weblogic.cluster.ClusterRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.CoherenceClusterMetricsRuntimeMBean", "weblogic.cacheprovider.coherence.management.CoherenceClusterMetricsRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.CoherenceClusterRuntimeMBean", "weblogic.cacheprovider.coherence.management.CoherenceClusterRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.CoherenceServerLifeCycleRuntimeMBean", "weblogic.server.CoherenceServerLifeCycleRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.CoherenceServerLifeCycleTaskRuntimeMBean", "weblogic.server.CoherenceServerLifeCycleTaskRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ComponentConcurrentRuntimeMBean", "weblogic.j2ee.ComponentConcurrentRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ComponentRuntimeMBean", "weblogic.j2ee.ComponentRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ConcurrentManagedObjectsRuntimeMBean", "weblogic.work.concurrent.runtime.ConcurrentManagedObjectsRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ConnectorComponentRuntimeMBean", "weblogic.connector.monitoring.ConnectorComponentRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ConnectorConnectionPoolRuntimeMBean", "weblogic.connector.monitoring.outbound.ConnectionPoolRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ConnectorConnectionRuntimeMBean", "weblogic.connector.monitoring.outbound.ConnectionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ConnectorInboundRuntimeMBean", "weblogic.connector.monitoring.inbound.ConnectorInboundRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ConnectorServiceRuntimeMBean", "weblogic.connector.monitoring.ServiceRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ConnectorWorkManagerRuntimeMBean", "weblogic.connector.monitoring.work.ConnectorWorkManagerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ConsoleRuntimeMBean", "weblogic.console.internal.ConsoleRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.CursorRuntimeMBean", "weblogic.messaging.runtime.CursorRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.DeployerRuntimeMBean", "weblogic.management.deploy.internal.DeployerRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.DeploymentManagerMBean", "weblogic.management.deploy.internal.DeploymentManagerImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.DeploymentProgressObjectMBean", "weblogic.management.deploy.internal.DeploymentProgressObjectImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.DeploymentRequestTaskRuntimeMBean", "weblogic.deploy.service.internal.DeploymentRequestTaskRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.DeploymentTaskRuntimeMBean", "weblogic.management.deploy.DeploymentTaskRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.DomainPartitionRuntimeMBean", "weblogic.t3.srvr.DomainPartitionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.DomainRuntimeMBean", "weblogic.management.provider.internal.DomainRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EJBCacheRuntimeMBean", "weblogic.ejb.container.monitoring.EJBCacheRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EJBComponentRuntimeMBean", "weblogic.ejb.container.internal.EJBComponentRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EJBLockingRuntimeMBean", "weblogic.ejb.container.monitoring.EJBLockingRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EJBPoolRuntimeMBean", "weblogic.ejb.container.monitoring.EJBPoolRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EJBRuntimeMBean", "weblogic.ejb.container.monitoring.EJBRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EJBTimerRuntimeMBean", "weblogic.ejb.container.monitoring.EJBTimerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EJBTransactionRuntimeMBean", "weblogic.ejb.container.monitoring.EJBTransactionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EditSessionConfigurationManagerMBean", "weblogic.management.provider.internal.EditSessionConfigurationManagerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EditSessionConfigurationRuntimeMBean", "weblogic.management.provider.internal.EditSessionConfigurationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ElasticServiceManagerRuntimeMBean", "weblogic.elasticity.ElasticServiceManagerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EntityCacheCumulativeRuntimeMBean", "weblogic.xml.util.cache.entitycache.EntityCacheCumulativeStatsBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EntityCacheCurrentStateRuntimeMBean", "weblogic.xml.util.cache.entitycache.EntityCacheCurrentStatsBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EntityCacheRuntimeMBean", "weblogic.xml.util.cache.entitycache.EntityCacheStatsBeanInfo");
      interfaceMap.put("weblogic.management.runtime.EntityEJBRuntimeMBean", "weblogic.ejb.container.monitoring.EntityEJBRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ExecuteQueueRuntimeMBean", "weblogic.kernel.ExecuteQueueRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.InterceptionComponentRuntimeMBean", "weblogic.messaging.interception.module.InterceptionComponentBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCAbstractDataSourceRuntimeMBean", "weblogic.jdbc.common.internal.AbstractDataSourceRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCDataSourceRuntimeMBean", "weblogic.jdbc.common.internal.DataSourceRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCDataSourceTaskRuntimeMBean", "weblogic.jdbc.common.internal.JDBCDataSourceTaskRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCDriverRuntimeMBean", "weblogic.jdbc.common.internal.DriverRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCMultiDataSourceRuntimeMBean", "weblogic.jdbc.common.internal.MultiDataSourceRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCOracleDataSourceInstanceRuntimeMBean", "weblogic.jdbc.common.internal.OracleDataSourceInstanceRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCOracleDataSourceRuntimeMBean", "weblogic.jdbc.common.internal.OracleDataSourceRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCPartitionRuntimeMBean", "weblogic.jdbc.common.internal.JDBCPartitionRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCProxyDataSourceRuntimeMBean", "weblogic.jdbc.common.internal.ProxyDataSourceRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCReplayStatisticsRuntimeMBean", "weblogic.jdbc.common.internal.JDBCReplayStatisticsRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCServiceRuntimeMBean", "weblogic.jdbc.common.internal.ServiceRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JDBCUCPDataSourceRuntimeMBean", "weblogic.jdbc.common.internal.UCPDataSourceRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSComponentRuntimeMBean", "weblogic.jms.module.JMSComponentBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSConnectionRuntimeMBean", "weblogic.jms.frontend.FEConnectionRuntimeDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSConsumerRuntimeMBean", "weblogic.jms.frontend.FEConsumerBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSDestinationRuntimeMBean", "weblogic.jms.backend.BEDestinationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSDurableSubscriberRuntimeMBean", "weblogic.jms.backend.BEDurableSubscriberRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSMessageCursorRuntimeMBean", "weblogic.jms.backend.JMSMessageCursorRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSMessageManagementRuntimeMBean", "weblogic.jms.backend.BEMessageManagementRuntimeDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSPooledConnectionRuntimeMBean", "weblogic.deployment.jms.JMSSessionPoolRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSProducerRuntimeMBean", "weblogic.jms.frontend.FEProducerBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSRemoteEndpointRuntimeMBean", "weblogic.jms.saf.SAFRemoteEndpointRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSRuntimeMBean", "weblogic.jms.JMSServiceBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSServerRuntimeMBean", "weblogic.jms.backend.JMSServerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSSessionPoolRuntimeMBean", "weblogic.jms.backend.BEServerSessionPoolBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JMSSessionRuntimeMBean", "weblogic.jms.frontend.FESessionBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JRockitRuntimeMBean", "weblogic.t3.srvr.JRockitRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JTAPartitionRuntimeMBean", "weblogic.transaction.internal.JTAPartitionRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JTARecoveryRuntimeMBean", "weblogic.transaction.internal.JTARecoveryRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JTARuntimeMBean", "weblogic.transaction.internal.JTARuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JTAStatisticsRuntimeMBean", "weblogic.transaction.internal.JTAStatisticsImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JTATransactionStatisticsRuntimeMBean", "weblogic.transaction.internal.JTATransactionStatisticsImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JVMRuntimeMBean", "weblogic.t3.srvr.JVMRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsApplicationRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsApplicationMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsExceptionMapperStatisticsRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsExceptionMapperStatisticsMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsExecutionStatisticsRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsExecutionStatisticsMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsMonitoringInfoRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsMonitoringInfoMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsResourceConfigTypeRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsResourceConfigTypeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsResourceMethodBaseRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsResourceMethodBaseMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsResourceMethodRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsResourceMethodMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsResourceRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsResourceMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsResponseStatisticsRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsResponseStatisticsMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsSubResourceLocatorRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsSubResourceLocatorMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JaxRsUriRuntimeMBean", "weblogic.jaxrs.monitoring.impl.JaxRsUriMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JobRuntimeMBean", "weblogic.scheduler.JobRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JobSchedulerRuntimeMBean", "weblogic.scheduler.JobSchedulerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JoltConnectionPoolRuntimeMBean", "bea.jolt.pool.servlet.weblogic.ConnectionPoolRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JoltConnectionRuntimeMBean", "bea.jolt.pool.servlet.weblogic.ConnectionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.JoltConnectionServiceRuntimeMBean", "bea.jolt.pool.servlet.weblogic.PoolManagerStartUpJMXBeanInfo");
      interfaceMap.put("weblogic.management.runtime.KodoDataCacheRuntimeMBean", "weblogic.kodo.monitoring.KodoDataCacheRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.KodoPersistenceUnitRuntimeMBean", "weblogic.kodo.monitoring.KodoPersistenceUnitRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.KodoQueryCacheRuntimeMBean", "weblogic.kodo.monitoring.KodoQueryCacheRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.KodoQueryCompilationCacheRuntimeMBean", "weblogic.kodo.monitoring.KodoQueryCompilationCacheRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.LdapAuthenticatorRuntimeMBean", "weblogic.security.LdapAuthenticatorRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.LibDeploymentRuntimeMBean", "weblogic.management.deploy.internal.LibDeploymentRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.LibraryRuntimeMBean", "weblogic.application.internal.library.LibraryRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.LogBroadcasterRuntimeMBean", "weblogic.management.logging.LogBroadcasterBeanInfo");
      interfaceMap.put("weblogic.management.runtime.LogRuntimeMBean", "weblogic.management.logging.LogRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MANAsyncReplicationRuntimeMBean", "weblogic.cluster.replication.MANAsyncReplicationRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MANReplicationRuntimeMBean", "weblogic.cluster.replication.MANReplicationRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MailSessionRuntimeMBean", "weblogic.j2ee.MailSessionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ManagedExecutorServiceRuntimeMBean", "weblogic.work.concurrent.runtime.ManagedExecutorServiceRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ManagedScheduledExecutorServiceRuntimeMBean", "weblogic.work.concurrent.runtime.ManagedScheduledExecutorServiceRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ManagedThreadFactoryRuntimeMBean", "weblogic.work.concurrent.runtime.ManagedThreadFactoryRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MaxThreadsConstraintRuntimeMBean", "weblogic.work.MaxThreadsConstraintRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MessageCursorRuntimeMBean", "weblogic.messaging.kernel.runtime.MessageCursorRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MessageDrivenControlEJBRuntimeMBean", "weblogic.ejb.container.monitoring.MessageDrivenControlEJBRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MessageDrivenEJBRuntimeMBean", "weblogic.ejb.container.monitoring.MessageDrivenEJBRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MessagingBridgeRuntimeMBean", "weblogic.jms.bridge.internal.MessagingBridgeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MigratableServiceCoordinatorRuntimeMBean", "weblogic.cluster.migration.management.MigratableServiceCoordinatorRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MigrationDataRuntimeMBean", "weblogic.cluster.singleton.MigrationDataRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MigrationTaskRuntimeMBean", "weblogic.cluster.migration.management.MigrationTaskBeanInfo");
      interfaceMap.put("weblogic.management.runtime.MinThreadsConstraintRuntimeMBean", "weblogic.work.MinThreadsConstraintRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.NodeManagerRuntimeMBean", "weblogic.nodemanager.mbean.NodeManagerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.NonXAResourceRuntimeMBean", "weblogic.transaction.internal.NonXAResourceRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ONSClientRuntimeMBean", "weblogic.jdbc.common.internal.ONSClientRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ONSDaemonRuntimeMBean", "weblogic.jdbc.common.internal.ONSDaemonRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.OwsmSecurityPolicyRuntimeMBean", "weblogic.wsee.policy.mbean.OwsmSecurityPolicyRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PSAssemblyRuntimeMBean", "weblogic.messaging.path.PSAssemblyRuntimeDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PSEntryCursorRuntimeMBean", "weblogic.messaging.path.PSEntryCursorRuntimeDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PageFlowActionRuntimeMBean", "weblogic.servlet.internal.PageFlowActionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PageFlowRuntimeMBean", "weblogic.servlet.internal.PageFlowRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PageFlowsRuntimeMBean", "weblogic.servlet.internal.PageFlowsRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PartitionFairShareRuntimeMBean", "weblogic.work.PartitionFairShareRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PartitionLifeCycleRuntimeMBean", "weblogic.server.PartitionLifeCycleRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PartitionLifeCycleTaskRuntimeMBean", "weblogic.server.PartitionLifeCycleTaskRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PartitionMinThreadsConstraintCapRuntimeMBean", "weblogic.work.PartitionMinThreadsConstraintCapRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PartitionResourceMetricsRuntimeMBean", "weblogic.diagnostics.metrics.PartitionResourceMetricsRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PartitionRuntimeMBean", "weblogic.t3.srvr.PartitionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PartitionUserFileSystemManagerMBean", "weblogic.management.partition.admin.PartitionUserFileSystemManagerMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PartitionWorkManagerRuntimeMBean", "weblogic.work.PartitionWorkManagerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PathServiceRuntimeMBean", "weblogic.messaging.path.PathServiceRuntimeDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PersistenceUnitRuntimeMBean", "weblogic.persistence.PersistenceUnitRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PersistentStoreConnectionRuntimeMBean", "weblogic.store.admin.PersistentStoreConnectionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.PersistentStoreRuntimeMBean", "weblogic.store.admin.PersistentStoreRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ProgressMBean", "weblogic.server.ProgressMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ProviderRuntimeMBean", "weblogic.security.ProviderRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.QueryCacheRuntimeMBean", "weblogic.ejb.container.monitoring.QueryCacheRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.RealmRuntimeMBean", "weblogic.security.RealmRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ReplicationRuntimeMBean", "weblogic.management.runtime.ReplicationRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.RequestClassRuntimeMBean", "weblogic.work.RequestClassRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ResourceGroupLifeCycleRuntimeMBean", "weblogic.server.ResourceGroupLifeCycleRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ResourceGroupLifeCycleTaskRuntimeMBean", "weblogic.server.ResourceGroupLifeCycleTaskRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.RolloutServiceRuntimeMBean", "weblogic.management.patching.RolloutServiceFacadeMBeanBeanInfo");
      interfaceMap.put("weblogic.management.runtime.RolloutTaskRuntimeMBean", "weblogic.management.patching.RolloutProgressMBeanDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.RuntimeMBean", "weblogic.management.runtime.RuntimeMBeanDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SAFAgentRuntimeMBean", "weblogic.jms.saf.SAFAgentRuntimeMBeanAggregatorBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SAFConversationRuntimeMBean", "weblogic.messaging.saf.internal.ConversationRuntimeDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SAFMessageCursorRuntimeMBean", "weblogic.messaging.saf.internal.SAFMessageCursorRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SAFRemoteEndpointRuntimeMBean", "weblogic.jms.saf.SAFRemoteEndpointCustomizerBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SAFRuntimeMBean", "weblogic.jms.saf.SAFRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SAFStatisticsCommonMBean", "weblogic.messaging.saf.internal.SAFStatisticsCommonMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SCACompositeRuntimeMBean", "weblogic.sca.runtime.impl.SCACompositeRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SCAPojoComponentRuntimeMBean", "weblogic.sca.runtime.impl.SCAPojoComponentRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SCASpringComponentRuntimeMBean", "weblogic.sca.runtime.impl.SCASpringComponentRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SNMPAgentRuntimeMBean", "weblogic.diagnostics.snmp.server.SNMPAgentRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ScalingTaskRuntimeMBean", "weblogic.elasticity.ScalingTaskRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServerChannelRuntimeMBean", "weblogic.server.channels.ServerChannelRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServerLifeCycleRuntimeMBean", "weblogic.server.ServerLifeCycleRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServerLifeCycleTaskRuntimeMBean", "weblogic.server.ServerLifeCycleTaskRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServerLogRuntimeMBean", "weblogic.management.logging.ServerLogRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServerMigrationRuntimeMBean", "weblogic.cluster.singleton.ServerMigrationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServerRuntimeMBean", "weblogic.t3.srvr.ServerRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServerSecurityRuntimeMBean", "weblogic.security.SecurityRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServiceMigrationDataRuntimeMBean", "weblogic.cluster.singleton.ServiceMigrationDataRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServiceMigrationRuntimeMBean", "weblogic.cluster.singleton.ServiceMigrationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServletRuntimeMBean", "weblogic.servlet.internal.ServletRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ServletSessionRuntimeMBean", "weblogic.servlet.internal.session.ServletSessionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SessionHelperManagerRuntimeMBean", "weblogic.deploy.api.tools.remote.SessionHelperManagerRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SessionHelperRuntimeMBean", "weblogic.deploy.api.tools.remote.SessionHelperRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SingleSignOnServicesRuntimeMBean", "weblogic.security.SingleSignOnServicesRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SingletonEJBRuntimeMBean", "weblogic.ejb.container.monitoring.SingletonEJBRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SpringApplicationContextRuntimeMBean", "weblogic.spring.monitoring.SpringApplicationContextRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SpringBeanDefinitionRuntimeMBean", "weblogic.spring.monitoring.SpringBeanDefinitionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SpringRuntimeMBean", "weblogic.spring.monitoring.SpringRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SpringTransactionManagerRuntimeMBean", "weblogic.spring.monitoring.SpringTransactionManagerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SpringTransactionTemplateRuntimeMBean", "weblogic.spring.monitoring.SpringTransactionTemplateRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SpringViewResolverRuntimeMBean", "weblogic.spring.monitoring.SpringViewResolverRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SpringViewRuntimeMBean", "weblogic.spring.monitoring.SpringViewRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.StatefulEJBRuntimeMBean", "weblogic.ejb.container.monitoring.StatefulEJBRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.StatelessEJBRuntimeMBean", "weblogic.ejb.container.monitoring.StatelessEJBRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SystemComponentLifeCycleRuntimeMBean", "weblogic.server.SystemComponentLifeCycleRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.SystemComponentLifeCycleTaskRuntimeMBean", "weblogic.server.SystemComponentLifeCycleTaskRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.TaskRuntimeMBean", "weblogic.management.runtime.TaskRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.ThreadPoolRuntimeMBean", "weblogic.work.ThreadPoolRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.TimeServiceRuntimeMBean", "weblogic.time.server.TimerMBeanBeanInfo");
      interfaceMap.put("weblogic.management.runtime.TimerRuntimeMBean", "weblogic.timers.internal.TimerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.TransactionNameRuntimeMBean", "weblogic.transaction.internal.TransactionNameRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.TransactionResourceRuntimeMBean", "weblogic.transaction.internal.TransactionResourceRuntimeImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.URLResourceRuntimeMBean", "weblogic.servlet.internal.URLResourceRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.UnicastMessagingRuntimeMBean", "weblogic.cluster.messaging.internal.server.UnicastMessagingRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.UserLockoutManagerRuntimeMBean", "weblogic.security.UserLockoutManagerRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WANReplicationRuntimeMBean", "weblogic.servlet.cluster.WANReplicationRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFAccessRuntimeMBean", "weblogic.diagnostics.accessor.DiagnosticAccessRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFArchiveRuntimeMBean", "weblogic.diagnostics.archive.WLDFDiagnosticArchiveRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFControlRuntimeMBean", "weblogic.diagnostics.runtimecontrol.internal.WLDFControlRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFDataAccessRuntimeMBean", "weblogic.diagnostics.accessor.DiagnosticDataAccessRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFDataRetirementTaskRuntimeMBean", "weblogic.diagnostics.archive.WLDFDataRetirementByAgeTaskImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFDbstoreArchiveRuntimeMBean", "weblogic.diagnostics.archive.WLDFDiagnosticDbstoreArchiveRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFDebugPatchTaskRuntimeMBean", "weblogic.diagnostics.debugpatch.WLDFDebugPatchTaskRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFDebugPatchesRuntimeMBean", "weblogic.diagnostics.debugpatch.WLDFDebugPatchesRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFEditableArchiveRuntimeMBean", "weblogic.diagnostics.archive.WLDFDiagnosticEditableArchiveRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFFileArchiveRuntimeMBean", "weblogic.diagnostics.archive.WLDFDiagnosticFileArchiveRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFHarvesterManagerRuntimeMBean", "weblogic.diagnostics.runtimecontrol.internal.HarvesterManagerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFHarvesterRuntimeMBean", "weblogic.diagnostics.harvester.internal.HarvesterRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFImageCreationTaskRuntimeMBean", "weblogic.diagnostics.image.TaskRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFImageRuntimeMBean", "weblogic.diagnostics.image.ImageRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFInstrumentationRuntimeMBean", "weblogic.diagnostics.instrumentation.InstrumentationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFPartitionAccessRuntimeMBean", "weblogic.diagnostics.accessor.PartitionAccessRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFPartitionHarvesterRuntimeMBean", "weblogic.diagnostics.harvester.internal.PartitionHarvesterRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFPartitionImageRuntimeMBean", "weblogic.diagnostics.image.PartitionImageRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFPartitionRuntimeMBean", "weblogic.diagnostics.partition.WLDFPartitionRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFRuntimeMBean", "weblogic.diagnostics.lifecycle.WLDFRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFSystemResourceControlRuntimeMBean", "weblogic.diagnostics.runtimecontrol.internal.WLDFSystemResourceControlRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFWatchJMXNotificationRuntimeMBean", "weblogic.diagnostics.watch.JMXNotificationProducerBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFWatchManagerRuntimeMBean", "weblogic.diagnostics.runtimecontrol.internal.WatchManagerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFWatchNotificationRuntimeMBean", "weblogic.diagnostics.watch.WatchNotificationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFWatchNotificationSourceRuntimeMBean", "weblogic.diagnostics.watch.JMXNotificationSourceBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WLDFWlstoreArchiveRuntimeMBean", "weblogic.diagnostics.archive.WLDFDiagnosticWlstoreArchiveRuntimeBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WSRMRemoteEndpointRuntimeMBean", "weblogic.messaging.saf.internal.RemoteEndpointRuntimeDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WTCRuntimeMBean", "weblogic.wtc.gwt.WTCServiceBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WTCStatisticsRuntimeMBean", "weblogic.wtc.gwt.WTCStatisticsRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WebAppComponentRuntimeMBean", "weblogic.servlet.internal.WebAppRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WebPubSubRuntimeMBean", "weblogic.servlet.httppubsub.runtime.WebPubSubRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WebServerRuntimeMBean", "weblogic.servlet.internal.WebServerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WebsocketApplicationRuntimeMBean", "weblogic.websocket.tyrus.monitoring.WebsocketApplicationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WebsocketBaseRuntimeMBean", "weblogic.websocket.tyrus.monitoring.WebsocketBaseRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WebsocketEndpointRuntimeMBean", "weblogic.websocket.tyrus.monitoring.WebsocketEndpointRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WebsocketMessageStatisticsRuntimeMBean", "weblogic.websocket.tyrus.monitoring.WebsocketMessageStatisticsRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WorkManagerRuntimeMBean", "weblogic.work.WorkManagerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WorkflowTaskRuntimeMBean", "weblogic.management.workflow.mbean.WorkflowProgressMBeanDelegateBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeAggregatableBaseOperationRuntimeMBean", "weblogic.wsee.monitoring.WseeAggregatableBaseOperationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeBaseOperationRuntimeMBean", "weblogic.wsee.monitoring.WseeBaseOperationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeBasePortRuntimeMBean", "weblogic.wsee.monitoring.WseeBasePortRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeBaseRuntimeMBean", "weblogic.wsee.monitoring.WseeBaseRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeClientConfigurationRuntimeMBean", "weblogic.wsee.monitoring.WseeClientConfigurationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeClientOperationRuntimeMBean", "weblogic.wsee.monitoring.WseeClientOperationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeClientPortRuntimeMBean", "weblogic.wsee.monitoring.WseeClientPortRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeClientRuntimeMBean", "weblogic.wsee.monitoring.WseeClientRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeClusterFrontEndRuntimeMBean", "weblogic.wsee.monitoring.WseeClusterFrontEndRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeClusterRoutingRuntimeMBean", "weblogic.wsee.monitoring.WseeClusterRoutingRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeHandlerRuntimeMBean", "weblogic.wsee.monitoring.WseeHandlerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeMcRuntimeMBean", "weblogic.wsee.mc.mbean.WseeMcRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeOperationConfigurationRuntimeMBean", "weblogic.wsee.monitoring.WseeOperationConfigurationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeOperationRuntimeMBean", "weblogic.wsee.monitoring.WseeOperationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseePolicyRuntimeMBean", "weblogic.wsee.policy.mbean.WseePolicyRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseePolicySubjectManagerRuntimeMBean", "weblogic.wsee.policy.deployment.WseePolicySubjectManagerRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseePortConfigurationRuntimeMBean", "weblogic.wsee.monitoring.WseePortConfigurationRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseePortPolicyRuntimeMBean", "weblogic.wsee.monitoring.WseePortPolicyRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseePortRuntimeMBean", "weblogic.wsee.monitoring.WseePortRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeRuntimeMBean", "weblogic.wsee.monitoring.WseeRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeV2RuntimeMBean", "weblogic.wsee.monitoring.WseeV2RuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.WseeWsrmRuntimeMBean", "weblogic.wsee.monitoring.WseeWsrmRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.XMLCacheCumulativeRuntimeMBean", "weblogic.xml.util.cache.entitycache.XMLCacheCumulativeRuntimeMBeanImplBeanInfo");
      interfaceMap.put("weblogic.management.runtime.XMLCacheMonitorRuntimeMBean", "weblogic.xml.util.cache.entitycache.XMLCacheMonitorRuntimeMBeanImplBeanInfo");
      roleInfoList = new ArrayList(96);
      roleInfoList.add("weblogic.management.runtime.AggregateProgressMBean");
      roleInfoList.add("weblogic.management.runtime.AppClientComponentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.AppDeploymentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.AppRuntimeStateRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ApplicationRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.CoherenceClusterMetricsRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.CoherenceClusterRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.CoherenceServerLifeCycleRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.CoherenceServerLifeCycleTaskRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ComponentConcurrentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ComponentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ConcurrentManagedObjectsRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ConnectorComponentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ConnectorServiceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ConsoleRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.DeployerRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.DeploymentManagerMBean");
      roleInfoList.add("weblogic.management.runtime.DeploymentProgressObjectMBean");
      roleInfoList.add("weblogic.management.runtime.DeploymentTaskRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.DomainPartitionRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.DomainRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.EJBComponentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.EJBPoolRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.EJBTransactionRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.EditSessionConfigurationManagerMBean");
      roleInfoList.add("weblogic.management.runtime.EditSessionConfigurationRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.InterceptionComponentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JDBCAbstractDataSourceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JDBCDataSourceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JDBCMultiDataSourceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JDBCOracleDataSourceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JDBCProxyDataSourceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JDBCReplayStatisticsRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JDBCUCPDataSourceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JMSComponentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JMSRemoteEndpointRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JTAPartitionRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JTARuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsApplicationRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsExceptionMapperStatisticsRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsExecutionStatisticsRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsMonitoringInfoRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsResourceConfigTypeRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsResourceMethodBaseRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsResourceMethodRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsResourceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsResponseStatisticsRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsSubResourceLocatorRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.JaxRsUriRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.LibDeploymentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ManagedExecutorServiceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ManagedScheduledExecutorServiceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ManagedThreadFactoryRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.PartitionLifeCycleRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.PartitionLifeCycleTaskRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.PartitionRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ProgressMBean");
      roleInfoList.add("weblogic.management.runtime.RealmRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.RequestClassRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ResourceGroupLifeCycleRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ResourceGroupLifeCycleTaskRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.RolloutServiceRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.RolloutTaskRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SAFAgentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SAFMessageCursorRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SAFRemoteEndpointRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SCAPojoComponentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SCASpringComponentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ServerLifeCycleRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ServerLifeCycleTaskRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ServerRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ServerSecurityRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ServletRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SessionHelperManagerRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SessionHelperRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SingletonEJBRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.StatelessEJBRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SystemComponentLifeCycleRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.SystemComponentLifeCycleTaskRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.ThreadPoolRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.UserLockoutManagerRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WLDFAccessRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WLDFDataAccessRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WLDFHarvesterRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WLDFPartitionAccessRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WLDFPartitionRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WLDFRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WSRMRemoteEndpointRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WebAppComponentRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WebServerRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WebsocketApplicationRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WebsocketBaseRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WebsocketEndpointRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WebsocketMessageStatisticsRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WorkManagerRuntimeMBean");
      roleInfoList.add("weblogic.management.runtime.WseePolicySubjectManagerRuntimeMBean");
      SINGLETON = new BeanInfoFactory();
   }
}
