package weblogic.server;

public interface ServerStates {
   int SRVR_SHUTDOWN = 0;
   int SRVR_STARTING = 1;
   int SRVR_RUNNING = 2;
   int SRVR_STANDBY = 3;
   int SRVR_SUSPENDING = 4;
   int SRVR_FORCE_SUSPENDING = 5;
   int SRVR_RESUMING = 6;
   int SRVR_SHUTTING_DOWN = 7;
   int SRVR_FAILED = 8;
   int SRVR_UNKNOWN = 9;
   int SRVR_SHUTDOWN_PENDING = 10;
   int SRVR_SHUTDOWN_IN_PROCESS = 11;
   int SRVR_FAILED_RESTARTING = 12;
   int SRVR_ACTIVATE_LATER = 13;
   int SRVR_FAILED_NOT_RESTARTABLE = 14;
   int SRVR_FAILED_MIGRATABLE = 15;
   int SRVR_DISCOVERED = 16;
   int SRVR_ADMIN = 17;
   int SRVR_FORCE_SHUTTING_DOWN = 18;
   String SHUTDOWN = "SHUTDOWN";
   String STARTING = "STARTING";
   String RUNNING = "RUNNING";
   String RESTART_REQUIRED = "RESTART_REQUIRED";
   String STANDBY = "STANDBY";
   String ADMIN = "ADMIN";
   String SUSPENDING = "SUSPENDING";
   String FORCE_SUSPENDING = "FORCE_SUSPENDING";
   String RESUMING = "RESUMING";
   String SHUTTING_DOWN = "SHUTTING_DOWN";
   String FORCE_SHUTTING_DOWN = "FORCE_SHUTTING_DOWN";
   String FAILED = "FAILED";
   /** @deprecated */
   @Deprecated
   String SHUTDOWN_PENDING = "SHUTDOWN_PENDING";
   /** @deprecated */
   @Deprecated
   String SHUTDOWN_IN_PROCESS = "SHUTDOWN_IN_PROCESS";
   String UNKNOWN = "UNKNOWN";
   String DISCOVERED = "DISCOVERED";
   String FAILED_RESTARTING = "FAILED_RESTARTING";
   String ACTIVATE_LATER = "ACTIVATE_LATER";
   String FAILED_NOT_RESTARTABLE = "FAILED_NOT_RESTARTABLE";
   String FAILED_MIGRATABLE = "FAILED_MIGRATABLE";
   String[] SERVERSTATES = new String[]{"SHUTDOWN", "STARTING", "RUNNING", "STANDBY", "SUSPENDING", "FORCE_SUSPENDING", "RESUMING", "SHUTTING_DOWN", "FAILED", "UNKNOWN", "SHUTDOWN_PENDING", "SHUTDOWN_IN_PROCESS", "FAILED_RESTARTING", "ACTIVATE_LATER", "FAILED_NOT_RESTARTABLE", "FAILED_MIGRATABLE", "DISCOVERED", "ADMIN", "FORCE_SHUTTING_DOWN"};
}
