package weblogic.rmi.internal;

public interface DescriptorConstants {
   String WLS_RTD_PUBLIC_ID = "-//BEA Systems, Inc.//RMI Runtime DTD 1.0//EN";
   String WLS_RTD_SYSTEM_ID = "rmi.dtd";
   String WLS_RTD_LOCAL_DTD_NAME = "rmi.dtd";
   String XML_HEADER = "<?xml version='1.0' encoding='UTF-8'?>";
   String XML_DOCTYPE = "<!DOCTYPE rmi PUBLIC \"-//BEA Systems, Inc.//RMI Runtime DTD 1.0//EN\" \"rmi.dtd\">";
   String WLS_RMI_XSD_NAME = "rmi.xsd";
   String WLS_RMI_XML_NS = "http://xmlns.oracle.com/weblogic/rmi";
   String RMI_DESCRIPTOR = "rmidescriptor";
   String CLUSTER_DESCRIPTOR = "clusterdescriptor";
   String LIFECYCLE_DESCRIPTOR = "lifecycledescriptor";
   String METHOD_DESCRIPTOR = "methoddescriptor";
   String SECURITY_DESCRIPTOR = "securitydescriptor";
   String USE_SERVER_SIDE_STUBS = "use-server-side-stubs";
   String ENABLE_CALL_BY_REF = "enable-call-by-reference";
   String REMOTE_REF_CLASSNAME = "remote-ref-classname";
   String SERVER_REF_CLASSNAME = "server-ref-classname";
   String INITIAL_REFERENCE = "initial-reference";
   String NETWORK_ACCESS_POINT = "network-access-point";
   String DISPATCH_POLICY = "dispatch-policy";
   String DISPATCH_CONTEXT = "dispatch-context";
   String REQUEST = "request";
   String CLUSTERABLE = "clusterable";
   String PROPOGATE_ENVIRONMENT = "propagate-environment";
   String LOAD_ALGORITHM = "load-algorithm";
   String CALL_ROUTER_CLASSNAME = "call-router-classname";
   String REPLICA_HANDLER_CLASSNAME = "replica-handler-classname";
   String STICK_TO_FIRST_SERVER = "stick-to-first-server";
   String NAME = "name";
   String ONEWAY = "oneway";
   String TRANSACTIONAL = "transactional";
   String REQUIRES_TRANSACTION = "requires-transaction";
   String FUTURE = "future";
   String TIMEOUT = "timeout";
   String IDEMPOTENT = "idempotent";
   String ASYNCHRONOUS = "asynchronous";
   String ONE_WAY_TRAN_REQ = "oneway-transactional-request";
   String ONE_WAY_TRAN_RES = "oneway-transactional-response";
   String DGC_POLICY = "dgc-policy";
   String ACTIVATION_IDENTIFIER_CLASSNAME = "activation-identifier-classname";
   String DEACTIVATE_IMPL_ON_INVOKE = "deactivate-impl-on-invoke";
   String CONFIDENTIALITY = "confidentiality";
   String CLIENT_CERT_AUTHENTICATION = "client-cert-authentication";
   String CLIENT_AUTHENTICATION = "client-authentication";
   String IDENTITY_ASSERTION = "identity-assertion";
   String INTEGRITY = "integrity";
   String STATEFUL_AUTHENTICATION = "stateful-authentication";
   String REMOTE_EXCEPTION_WRAPPER_NAME = "remote-exception-wrapper-classname";
   String SCHEMA_LOCATION = "schemaLocation";
   String VERSION = "version";
}
