package pawt;

import org.python.compiler.APIVersion;
import org.python.compiler.Filename;
import org.python.compiler.MTime;
import org.python.core.CodeBootstrap;
import org.python.core.CodeLoader;
import org.python.core.Py;
import org.python.core.PyCode;
import org.python.core.PyFrame;
import org.python.core.PyFunctionTable;
import org.python.core.PyObject;
import org.python.core.PyRunnable;
import org.python.core.PyRunnableBootstrap;
import org.python.core.ThreadState;
import org.python.core.imp;

@APIVersion(37)
@MTime(1498849384000L)
@Filename("pawt/colors.py")
public class colors$py extends PyFunctionTable implements PyRunnable {
   static colors$py self;
   static final PyCode f$0;

   public PyObject f$0(PyFrame var1, ThreadState var2) {
      var1.setline(1);
      String[] var3 = new String[]{"Color"};
      PyObject[] var5 = imp.importFrom("java.awt", var3, var1, -1);
      PyObject var4 = var5[0];
      var1.setlocal("Color", var4);
      var4 = null;
      var1.setline(3);
      PyObject var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(240), (PyObject)Py.newInteger(248), (PyObject)Py.newInteger(255));
      var1.setlocal("aliceblue", var6);
      var3 = null;
      var1.setline(4);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(250), (PyObject)Py.newInteger(235), (PyObject)Py.newInteger(215));
      var1.setlocal("antiquewhite", var6);
      var3 = null;
      var1.setline(5);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(255));
      var1.setlocal("aqua", var6);
      var3 = null;
      var1.setline(6);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(127), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(212));
      var1.setlocal("aquamarine", var6);
      var3 = null;
      var1.setline(7);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(240), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(255));
      var1.setlocal("azure", var6);
      var3 = null;
      var1.setline(8);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(245), (PyObject)Py.newInteger(245), (PyObject)Py.newInteger(220));
      var1.setlocal("beige", var6);
      var3 = null;
      var1.setline(9);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(228), (PyObject)Py.newInteger(196));
      var1.setlocal("bisque", var6);
      var3 = null;
      var1.setline(10);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(0));
      var1.setlocal("black", var6);
      var3 = null;
      var1.setline(11);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(235), (PyObject)Py.newInteger(205));
      var1.setlocal("blanchedalmond", var6);
      var3 = null;
      var1.setline(12);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(255));
      var1.setlocal("blue", var6);
      var3 = null;
      var1.setline(13);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(138), (PyObject)Py.newInteger(43), (PyObject)Py.newInteger(226));
      var1.setlocal("blueviolet", var6);
      var3 = null;
      var1.setline(14);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(165), (PyObject)Py.newInteger(42), (PyObject)Py.newInteger(42));
      var1.setlocal("brown", var6);
      var3 = null;
      var1.setline(15);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(222), (PyObject)Py.newInteger(184), (PyObject)Py.newInteger(135));
      var1.setlocal("burlywood", var6);
      var3 = null;
      var1.setline(16);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(95), (PyObject)Py.newInteger(158), (PyObject)Py.newInteger(160));
      var1.setlocal("cadetblue", var6);
      var3 = null;
      var1.setline(17);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(127), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(0));
      var1.setlocal("chartreuse", var6);
      var3 = null;
      var1.setline(18);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(210), (PyObject)Py.newInteger(105), (PyObject)Py.newInteger(30));
      var1.setlocal("chocolate", var6);
      var3 = null;
      var1.setline(19);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(127), (PyObject)Py.newInteger(80));
      var1.setlocal("coral", var6);
      var3 = null;
      var1.setline(20);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(100), (PyObject)Py.newInteger(149), (PyObject)Py.newInteger(237));
      var1.setlocal("cornflowerblue", var6);
      var3 = null;
      var1.setline(21);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(248), (PyObject)Py.newInteger(220));
      var1.setlocal("cornsilk", var6);
      var3 = null;
      var1.setline(22);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(220), (PyObject)Py.newInteger(20), (PyObject)Py.newInteger(60));
      var1.setlocal("crimson", var6);
      var3 = null;
      var1.setline(23);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(255));
      var1.setlocal("cyan", var6);
      var3 = null;
      var1.setline(24);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(139));
      var1.setlocal("darkblue", var6);
      var3 = null;
      var1.setline(25);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(139), (PyObject)Py.newInteger(139));
      var1.setlocal("darkcyan", var6);
      var3 = null;
      var1.setline(26);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(184), (PyObject)Py.newInteger(134), (PyObject)Py.newInteger(11));
      var1.setlocal("darkgoldenrod", var6);
      var3 = null;
      var1.setline(27);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(169), (PyObject)Py.newInteger(169), (PyObject)Py.newInteger(169));
      var1.setlocal("darkgray", var6);
      var3 = null;
      var1.setline(28);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(100), (PyObject)Py.newInteger(0));
      var1.setlocal("darkgreen", var6);
      var3 = null;
      var1.setline(29);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(189), (PyObject)Py.newInteger(183), (PyObject)Py.newInteger(107));
      var1.setlocal("darkkhaki", var6);
      var3 = null;
      var1.setline(30);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(139), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(139));
      var1.setlocal("darkmagenta", var6);
      var3 = null;
      var1.setline(31);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(85), (PyObject)Py.newInteger(107), (PyObject)Py.newInteger(47));
      var1.setlocal("darkolivegreen", var6);
      var3 = null;
      var1.setline(32);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(140), (PyObject)Py.newInteger(0));
      var1.setlocal("darkorange", var6);
      var3 = null;
      var1.setline(33);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(153), (PyObject)Py.newInteger(50), (PyObject)Py.newInteger(204));
      var1.setlocal("darkorchid", var6);
      var3 = null;
      var1.setline(34);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(139), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(0));
      var1.setlocal("darkred", var6);
      var3 = null;
      var1.setline(35);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(233), (PyObject)Py.newInteger(150), (PyObject)Py.newInteger(122));
      var1.setlocal("darksalmon", var6);
      var3 = null;
      var1.setline(36);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(143), (PyObject)Py.newInteger(188), (PyObject)Py.newInteger(143));
      var1.setlocal("darkseagreen", var6);
      var3 = null;
      var1.setline(37);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(72), (PyObject)Py.newInteger(61), (PyObject)Py.newInteger(139));
      var1.setlocal("darkslateblue", var6);
      var3 = null;
      var1.setline(38);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(47), (PyObject)Py.newInteger(79), (PyObject)Py.newInteger(79));
      var1.setlocal("darkslategray", var6);
      var3 = null;
      var1.setline(39);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(206), (PyObject)Py.newInteger(209));
      var1.setlocal("darkturquoise", var6);
      var3 = null;
      var1.setline(40);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(148), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(211));
      var1.setlocal("darkviolet", var6);
      var3 = null;
      var1.setline(41);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(20), (PyObject)Py.newInteger(147));
      var1.setlocal("deeppink", var6);
      var3 = null;
      var1.setline(42);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(191), (PyObject)Py.newInteger(255));
      var1.setlocal("deepskyblue", var6);
      var3 = null;
      var1.setline(43);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(105), (PyObject)Py.newInteger(105), (PyObject)Py.newInteger(105));
      var1.setlocal("dimgray", var6);
      var3 = null;
      var1.setline(44);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(30), (PyObject)Py.newInteger(144), (PyObject)Py.newInteger(255));
      var1.setlocal("dodgerblue", var6);
      var3 = null;
      var1.setline(45);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(178), (PyObject)Py.newInteger(34), (PyObject)Py.newInteger(34));
      var1.setlocal("firebrick", var6);
      var3 = null;
      var1.setline(46);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(250), (PyObject)Py.newInteger(240));
      var1.setlocal("floralwhite", var6);
      var3 = null;
      var1.setline(47);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(34), (PyObject)Py.newInteger(139), (PyObject)Py.newInteger(34));
      var1.setlocal("forestgreen", var6);
      var3 = null;
      var1.setline(48);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(255));
      var1.setlocal("fuchsia", var6);
      var3 = null;
      var1.setline(49);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(220), (PyObject)Py.newInteger(220), (PyObject)Py.newInteger(220));
      var1.setlocal("gainsboro", var6);
      var3 = null;
      var1.setline(50);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(248), (PyObject)Py.newInteger(248), (PyObject)Py.newInteger(255));
      var1.setlocal("ghostwhite", var6);
      var3 = null;
      var1.setline(51);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(215), (PyObject)Py.newInteger(0));
      var1.setlocal("gold", var6);
      var3 = null;
      var1.setline(52);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(218), (PyObject)Py.newInteger(165), (PyObject)Py.newInteger(32));
      var1.setlocal("goldenrod", var6);
      var3 = null;
      var1.setline(53);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(128), (PyObject)Py.newInteger(128), (PyObject)Py.newInteger(128));
      var1.setlocal("gray", var6);
      var3 = null;
      var1.setline(54);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(128), (PyObject)Py.newInteger(0));
      var1.setlocal("green", var6);
      var3 = null;
      var1.setline(55);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(173), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(47));
      var1.setlocal("greenyellow", var6);
      var3 = null;
      var1.setline(56);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(240), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(240));
      var1.setlocal("honeydew", var6);
      var3 = null;
      var1.setline(57);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(105), (PyObject)Py.newInteger(180));
      var1.setlocal("hotpink", var6);
      var3 = null;
      var1.setline(58);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(205), (PyObject)Py.newInteger(92), (PyObject)Py.newInteger(92));
      var1.setlocal("indianred", var6);
      var3 = null;
      var1.setline(59);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(75), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(130));
      var1.setlocal("indigo", var6);
      var3 = null;
      var1.setline(60);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(240));
      var1.setlocal("ivory", var6);
      var3 = null;
      var1.setline(61);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(240), (PyObject)Py.newInteger(230), (PyObject)Py.newInteger(140));
      var1.setlocal("khaki", var6);
      var3 = null;
      var1.setline(62);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(230), (PyObject)Py.newInteger(230), (PyObject)Py.newInteger(250));
      var1.setlocal("lavender", var6);
      var3 = null;
      var1.setline(63);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(240), (PyObject)Py.newInteger(245));
      var1.setlocal("lavenderblush", var6);
      var3 = null;
      var1.setline(64);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(124), (PyObject)Py.newInteger(252), (PyObject)Py.newInteger(0));
      var1.setlocal("lawngreen", var6);
      var3 = null;
      var1.setline(65);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(250), (PyObject)Py.newInteger(205));
      var1.setlocal("lemonchiffon", var6);
      var3 = null;
      var1.setline(66);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(173), (PyObject)Py.newInteger(216), (PyObject)Py.newInteger(230));
      var1.setlocal("lightblue", var6);
      var3 = null;
      var1.setline(67);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(240), (PyObject)Py.newInteger(128), (PyObject)Py.newInteger(128));
      var1.setlocal("lightcoral", var6);
      var3 = null;
      var1.setline(68);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(224), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(255));
      var1.setlocal("lightcyan", var6);
      var3 = null;
      var1.setline(69);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(250), (PyObject)Py.newInteger(250), (PyObject)Py.newInteger(210));
      var1.setlocal("lightgoldenrodyellow", var6);
      var3 = null;
      var1.setline(70);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(144), (PyObject)Py.newInteger(238), (PyObject)Py.newInteger(144));
      var1.setlocal("lightgreen", var6);
      var3 = null;
      var1.setline(71);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(211), (PyObject)Py.newInteger(211), (PyObject)Py.newInteger(211));
      var1.setlocal("lightgrey", var6);
      var3 = null;
      var1.setline(72);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(182), (PyObject)Py.newInteger(193));
      var1.setlocal("lightpink", var6);
      var3 = null;
      var1.setline(73);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(160), (PyObject)Py.newInteger(122));
      var1.setlocal("lightsalmon", var6);
      var3 = null;
      var1.setline(74);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(32), (PyObject)Py.newInteger(178), (PyObject)Py.newInteger(170));
      var1.setlocal("lightseagreen", var6);
      var3 = null;
      var1.setline(75);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(135), (PyObject)Py.newInteger(206), (PyObject)Py.newInteger(250));
      var1.setlocal("lightskyblue", var6);
      var3 = null;
      var1.setline(76);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(119), (PyObject)Py.newInteger(136), (PyObject)Py.newInteger(153));
      var1.setlocal("lightslategray", var6);
      var3 = null;
      var1.setline(77);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(176), (PyObject)Py.newInteger(196), (PyObject)Py.newInteger(222));
      var1.setlocal("lightsteelblue", var6);
      var3 = null;
      var1.setline(78);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(224));
      var1.setlocal("lightyellow", var6);
      var3 = null;
      var1.setline(79);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(0));
      var1.setlocal("lime", var6);
      var3 = null;
      var1.setline(80);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(50), (PyObject)Py.newInteger(205), (PyObject)Py.newInteger(50));
      var1.setlocal("limegreen", var6);
      var3 = null;
      var1.setline(81);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(250), (PyObject)Py.newInteger(240), (PyObject)Py.newInteger(230));
      var1.setlocal("linen", var6);
      var3 = null;
      var1.setline(82);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(255));
      var1.setlocal("magenta", var6);
      var3 = null;
      var1.setline(83);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(128), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(0));
      var1.setlocal("maroon", var6);
      var3 = null;
      var1.setline(84);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(102), (PyObject)Py.newInteger(205), (PyObject)Py.newInteger(170));
      var1.setlocal("mediumaquamarine", var6);
      var3 = null;
      var1.setline(85);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(205));
      var1.setlocal("mediumblue", var6);
      var3 = null;
      var1.setline(86);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(186), (PyObject)Py.newInteger(85), (PyObject)Py.newInteger(211));
      var1.setlocal("mediumorchid", var6);
      var3 = null;
      var1.setline(87);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(147), (PyObject)Py.newInteger(112), (PyObject)Py.newInteger(219));
      var1.setlocal("mediumpurple", var6);
      var3 = null;
      var1.setline(88);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(60), (PyObject)Py.newInteger(179), (PyObject)Py.newInteger(113));
      var1.setlocal("mediumseagreen", var6);
      var3 = null;
      var1.setline(89);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(123), (PyObject)Py.newInteger(104), (PyObject)Py.newInteger(238));
      var1.setlocal("mediumslateblue", var6);
      var3 = null;
      var1.setline(90);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(250), (PyObject)Py.newInteger(154));
      var1.setlocal("mediumspringgreen", var6);
      var3 = null;
      var1.setline(91);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(72), (PyObject)Py.newInteger(209), (PyObject)Py.newInteger(204));
      var1.setlocal("mediumturquoise", var6);
      var3 = null;
      var1.setline(92);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(199), (PyObject)Py.newInteger(21), (PyObject)Py.newInteger(133));
      var1.setlocal("mediumvioletred", var6);
      var3 = null;
      var1.setline(93);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(25), (PyObject)Py.newInteger(25), (PyObject)Py.newInteger(112));
      var1.setlocal("midnightblue", var6);
      var3 = null;
      var1.setline(94);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(245), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(250));
      var1.setlocal("mintcream", var6);
      var3 = null;
      var1.setline(95);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(228), (PyObject)Py.newInteger(225));
      var1.setlocal("mistyrose", var6);
      var3 = null;
      var1.setline(96);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(228), (PyObject)Py.newInteger(181));
      var1.setlocal("moccasin", var6);
      var3 = null;
      var1.setline(97);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(222), (PyObject)Py.newInteger(173));
      var1.setlocal("navajowhite", var6);
      var3 = null;
      var1.setline(98);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(128));
      var1.setlocal("navy", var6);
      var3 = null;
      var1.setline(99);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(253), (PyObject)Py.newInteger(245), (PyObject)Py.newInteger(230));
      var1.setlocal("oldlace", var6);
      var3 = null;
      var1.setline(100);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(128), (PyObject)Py.newInteger(128), (PyObject)Py.newInteger(0));
      var1.setlocal("olive", var6);
      var3 = null;
      var1.setline(101);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(107), (PyObject)Py.newInteger(142), (PyObject)Py.newInteger(35));
      var1.setlocal("olivedrab", var6);
      var3 = null;
      var1.setline(102);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(165), (PyObject)Py.newInteger(0));
      var1.setlocal("orange", var6);
      var3 = null;
      var1.setline(103);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(69), (PyObject)Py.newInteger(0));
      var1.setlocal("orangered", var6);
      var3 = null;
      var1.setline(104);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(218), (PyObject)Py.newInteger(112), (PyObject)Py.newInteger(214));
      var1.setlocal("orchid", var6);
      var3 = null;
      var1.setline(105);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(238), (PyObject)Py.newInteger(232), (PyObject)Py.newInteger(170));
      var1.setlocal("palegoldenrod", var6);
      var3 = null;
      var1.setline(106);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(152), (PyObject)Py.newInteger(251), (PyObject)Py.newInteger(152));
      var1.setlocal("palegreen", var6);
      var3 = null;
      var1.setline(107);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(175), (PyObject)Py.newInteger(238), (PyObject)Py.newInteger(238));
      var1.setlocal("paleturquoise", var6);
      var3 = null;
      var1.setline(108);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(219), (PyObject)Py.newInteger(112), (PyObject)Py.newInteger(147));
      var1.setlocal("palevioletred", var6);
      var3 = null;
      var1.setline(109);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(239), (PyObject)Py.newInteger(213));
      var1.setlocal("papayawhip", var6);
      var3 = null;
      var1.setline(110);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(218), (PyObject)Py.newInteger(185));
      var1.setlocal("peachpuff", var6);
      var3 = null;
      var1.setline(111);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(205), (PyObject)Py.newInteger(133), (PyObject)Py.newInteger(63));
      var1.setlocal("peru", var6);
      var3 = null;
      var1.setline(112);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(192), (PyObject)Py.newInteger(203));
      var1.setlocal("pink", var6);
      var3 = null;
      var1.setline(113);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(221), (PyObject)Py.newInteger(160), (PyObject)Py.newInteger(221));
      var1.setlocal("plum", var6);
      var3 = null;
      var1.setline(114);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(176), (PyObject)Py.newInteger(224), (PyObject)Py.newInteger(230));
      var1.setlocal("powderblue", var6);
      var3 = null;
      var1.setline(115);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(128), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(128));
      var1.setlocal("purple", var6);
      var3 = null;
      var1.setline(116);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(0), (PyObject)Py.newInteger(0));
      var1.setlocal("red", var6);
      var3 = null;
      var1.setline(117);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(188), (PyObject)Py.newInteger(143), (PyObject)Py.newInteger(143));
      var1.setlocal("rosybrown", var6);
      var3 = null;
      var1.setline(118);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(65), (PyObject)Py.newInteger(105), (PyObject)Py.newInteger(225));
      var1.setlocal("royalblue", var6);
      var3 = null;
      var1.setline(119);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(139), (PyObject)Py.newInteger(69), (PyObject)Py.newInteger(19));
      var1.setlocal("saddlebrown", var6);
      var3 = null;
      var1.setline(120);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(250), (PyObject)Py.newInteger(128), (PyObject)Py.newInteger(114));
      var1.setlocal("salmon", var6);
      var3 = null;
      var1.setline(121);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(244), (PyObject)Py.newInteger(164), (PyObject)Py.newInteger(96));
      var1.setlocal("sandybrown", var6);
      var3 = null;
      var1.setline(122);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(46), (PyObject)Py.newInteger(139), (PyObject)Py.newInteger(87));
      var1.setlocal("seagreen", var6);
      var3 = null;
      var1.setline(123);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(245), (PyObject)Py.newInteger(238));
      var1.setlocal("seashell", var6);
      var3 = null;
      var1.setline(124);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(160), (PyObject)Py.newInteger(82), (PyObject)Py.newInteger(45));
      var1.setlocal("sienna", var6);
      var3 = null;
      var1.setline(125);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(192), (PyObject)Py.newInteger(192), (PyObject)Py.newInteger(192));
      var1.setlocal("silver", var6);
      var3 = null;
      var1.setline(126);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(135), (PyObject)Py.newInteger(206), (PyObject)Py.newInteger(235));
      var1.setlocal("skyblue", var6);
      var3 = null;
      var1.setline(127);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(106), (PyObject)Py.newInteger(90), (PyObject)Py.newInteger(205));
      var1.setlocal("slateblue", var6);
      var3 = null;
      var1.setline(128);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(112), (PyObject)Py.newInteger(128), (PyObject)Py.newInteger(144));
      var1.setlocal("slategray", var6);
      var3 = null;
      var1.setline(129);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(250), (PyObject)Py.newInteger(250));
      var1.setlocal("snow", var6);
      var3 = null;
      var1.setline(130);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(127));
      var1.setlocal("springgreen", var6);
      var3 = null;
      var1.setline(131);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(70), (PyObject)Py.newInteger(130), (PyObject)Py.newInteger(180));
      var1.setlocal("steelblue", var6);
      var3 = null;
      var1.setline(132);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(210), (PyObject)Py.newInteger(180), (PyObject)Py.newInteger(140));
      var1.setlocal("tan", var6);
      var3 = null;
      var1.setline(133);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(0), (PyObject)Py.newInteger(128), (PyObject)Py.newInteger(128));
      var1.setlocal("teal", var6);
      var3 = null;
      var1.setline(134);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(216), (PyObject)Py.newInteger(191), (PyObject)Py.newInteger(216));
      var1.setlocal("thistle", var6);
      var3 = null;
      var1.setline(135);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(99), (PyObject)Py.newInteger(71));
      var1.setlocal("tomato", var6);
      var3 = null;
      var1.setline(136);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(64), (PyObject)Py.newInteger(224), (PyObject)Py.newInteger(208));
      var1.setlocal("turquoise", var6);
      var3 = null;
      var1.setline(137);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(238), (PyObject)Py.newInteger(130), (PyObject)Py.newInteger(238));
      var1.setlocal("violet", var6);
      var3 = null;
      var1.setline(138);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(245), (PyObject)Py.newInteger(222), (PyObject)Py.newInteger(179));
      var1.setlocal("wheat", var6);
      var3 = null;
      var1.setline(139);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(255));
      var1.setlocal("white", var6);
      var3 = null;
      var1.setline(140);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(245), (PyObject)Py.newInteger(245), (PyObject)Py.newInteger(245));
      var1.setlocal("whitesmoke", var6);
      var3 = null;
      var1.setline(141);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(255), (PyObject)Py.newInteger(255), (PyObject)Py.newInteger(0));
      var1.setlocal("yellow", var6);
      var3 = null;
      var1.setline(142);
      var6 = var1.getname("Color").__call__((ThreadState)var2, Py.newInteger(154), (PyObject)Py.newInteger(205), (PyObject)Py.newInteger(50));
      var1.setlocal("yellowgreen", var6);
      var3 = null;
      var1.setline(144);
      var1.dellocal("Color");
      var1.f_lasti = -1;
      return Py.None;
   }

   public colors$py(String var1) {
      self = this;
      String[] var2 = new String[0];
      f$0 = Py.newCode(0, var2, var1, "<module>", 0, false, false, self, 0, (String[])null, (String[])null, 0, 4096);
   }

   public PyCode getMain() {
      return f$0;
   }

   public static void main(String[] var0) {
      Py.runMain(CodeLoader.createSimpleBootstrap((new colors$py("pawt/colors$py")).getMain()), var0);
   }

   public static CodeBootstrap getCodeBootstrap() {
      return PyRunnableBootstrap.getFilenameConstructorReflectionBootstrap(colors$py.class);
   }

   public PyObject call_function(int var1, PyFrame var2, ThreadState var3) {
      switch (var1) {
         case 0:
            return this.f$0(var2, var3);
         default:
            return null;
      }
   }
}
