package weblogic.jdbc.rowset;

import weblogic.xml.stream.Attribute;
import weblogic.xml.stream.ElementFactory;
import weblogic.xml.stream.XMLName;

public interface XMLSchemaConstants {
   String SCHEMA_INSTANCE_NS = "http://www.w3.org/2001/XMLSchema-instance";
   String SCHEMA_INSTANCE_PREFIX = "xsi";
   String SCHEMA_NS = "http://www.w3.org/2001/XMLSchema";
   String SCHEMA_PREFIX = "xsd";
   String WLDATA_PREFIX = "wld";
   String WL_DATA_NS = "http://www.bea.com/2002/10/weblogicdata";
   int WL_METADATA_VERSION_ONE = 1;
   int WL_METADATA_VERSION_TWO = 2;
   XMLName ANY_ATTRIBUTE_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "anyAttribute", "xsd");
   XMLName ATTRIBUTE_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "attribute", "xsd");
   XMLName CHOICE_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "choice", "xsd");
   XMLName COMPLEX_TYPE_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "complexType", "xsd");
   XMLName ELEMENT_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "element", "xsd");
   XMLName ENUM_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "enumeration", "xsd");
   XMLName NILLABLE_NAME = ElementFactory.createXMLName("nillable");
   XMLName RESTRICTION_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "restriction", "xsd");
   XMLName SCHEMA_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "schema", "xsd");
   XMLName SEQUENCE_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "sequence", "xsd");
   XMLName WLDD_AUTO = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "AutoIncrement", "wld");
   XMLName WLDD_DEFINITELY_WRITABLE = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "DefinitelyWritable", "wld");
   XMLName WLDD_DEFAULT_NAMESPACE = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "DefaultNamespace", "wld");
   XMLName WLDD_JDBC_TYPE = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "JDBCType", "wld");
   XMLName WLDD_OPTPOLICY = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "OptimisticPolicy", "wld");
   XMLName WLDD_PK = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "PrimaryKey", "wld");
   XMLName WLDD_READONLY = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "ReadOnly", "wld");
   XMLName WLDD_ROWID = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "RowId", "wld");
   XMLName WLDD_ROWSET = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "RowSet", "wld");
   XMLName WLDD_ROWSTATE = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "RowState", "wld");
   XMLName WLDD_SELECTED = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "Selected", "wld");
   XMLName WLDD_TABLE_NAME = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "TableName", "wld");
   XMLName WLDD_AUTO_VERSION = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "AutoVersion", "wld");
   XMLName WLDD_VERSION = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "VersionColumn", "wld");
   XMLName WLDD_WRITECOL = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "WriteColumnName", "wld");
   XMLName WLDD_WRITE_TABLE_NAME = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "WriteTable", "wld");
   XMLName WLDD_METADATA_VERSION = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "MetaDataVersion", "wld");
   XMLName WLDD_VALID_METADATA = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "ValidMetaData", "wld");
   XMLName WLDD_MAX_CATALOG_NAME_LENGTH = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "MaxCatalogNameLength", "wld");
   XMLName WLDD_MAX_SCHEMA_NAME_LENGTH = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "MaxSchemaNameLength", "wld");
   XMLName WLDD_MAX_TABLE_NAME_LENGTH = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "MaxTableNameLength", "wld");
   XMLName WLDD_IDENTIFIER_QUOTE_STRING = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "IdentifierQuoteString", "wld");
   XMLName WLDD_CATALOG_SEPARATOR = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "CatalogSeparator", "wld");
   XMLName WLDD_CATALOG_AT_START = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "CatalogAtStart", "wld");
   XMLName WLDD_SUPPORTS_SCHEMAS_IN_DML = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "SupportsSchemasInDataManipulation", "wld");
   XMLName WLDD_SUPPORTS_CATALOGS_IN_DML = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "SupportsCatalogsInDataManipulation", "wld");
   XMLName WLDD_STORES_UPPER_CASE_IDENTIFIERS = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "StoresUpperCaseIdentifiers", "wld");
   XMLName WLDD_STORES_LOWER_CASE_IDENTIFIERS = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "StoresLowerCaseIdentifiers", "wld");
   XMLName WLDD_STORES_MIXED_CASE_IDENTIFIERS = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "StoresMixedCaseIdentifiers", "wld");
   XMLName WLDD_STORES_UPPER_CASE_QUOTED_IDENTIFIERS = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "StoresUpperCaseQuotedIdentifiers", "wld");
   XMLName WLDD_STORES_LOWER_CASE_QUOTED_IDENTIFIERS = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "StoresLowerCaseQuotedIdentifiers", "wld");
   XMLName WLDD_STORES_MIXED_CASE_QUOTED_IDENTIFIERS = ElementFactory.createXMLName("http://www.bea.com/2002/10/weblogicdata", "StoresMixedCaseQuotedIdentifiers", "wld");
   XMLName NIL_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema-instance", "nil", "xsi");
   XMLName SCHEMA_LOCATION_NAME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema-instance", "schemaLocation", "xsi");
   Attribute ATTRIBUTE_FORM_DEFAULT_ATTR = ElementFactory.createAttribute("attributeFormDefault", "unqualified");
   Attribute ELEMENT_FORM_DEFAULT_ATTR = ElementFactory.createAttribute("elementFormDefault", "qualified");
   Attribute ISREADONLY_ATTR = ElementFactory.createAttribute(WLDD_READONLY, "true");
   Attribute ISROWSET_ATTR = ElementFactory.createAttribute(WLDD_ROWSET, "true");
   Attribute NIL_ATTR = ElementFactory.createAttribute("nillable", "true");
   Attribute SCHEMA_INSTANCE_NAMESPACE = ElementFactory.createNamespaceAttribute("xsi", "http://www.w3.org/2001/XMLSchema-instance");
   Attribute SCHEMA_NAMESPACE = ElementFactory.createNamespaceAttribute("xsd", "http://www.w3.org/2001/XMLSchema");
   Attribute WLDATA_NAMESPACE = ElementFactory.createNamespaceAttribute("wld", "http://www.bea.com/2002/10/weblogicdata");
   XMLName XSD_BASE64BINARY = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "base64Binary", "xsd");
   XMLName XSD_BOOLEAN = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "boolean", "xsd");
   XMLName XSD_BYTE = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "byte", "xsd");
   XMLName XSD_DATETIME = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "dateTime", "xsd");
   XMLName XSD_DECIMAL = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "decimal", "xsd");
   XMLName XSD_DOUBLE = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "double", "xsd");
   XMLName XSD_FLOAT = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "float", "xsd");
   XMLName XSD_INT = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "int", "xsd");
   XMLName XSD_INTEGER = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "integer", "xsd");
   XMLName XSD_LONG = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "long", "xsd");
   XMLName XSD_SHORT = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "short", "xsd");
   XMLName XSD_STRING = ElementFactory.createXMLName("http://www.w3.org/2001/XMLSchema", "string", "xsd");
}
