package weblogic.servlet.internal.dd;

import weblogic.utils.io.XMLWriter;

public interface ToXML {
   String INVALID_WELCOME_FILE = "INVALID_WELCOME_FILE";
   String NO_ROLE_NAMES = "NO_ROLE_NAMES";
   String INVALID_ERROR_CODE = "INVALID_ERROR_CODE";
   String MULTIPLE_DEFINES_ERROR_PAGE = "MULTIPLE_DEFINES_ERROR_PAGE";
   String NO_ERROR_PAGE_LOCATION = "NO_ERROR_PAGE_LOCATION";
   String NO_LOGIN_PAGE = "NO_LOGIN_PAGE";
   String NO_LOGIN_ERROR_PAGE = "NO_LOGIN_ERROR_PAGE";
   String NO_MIME_EXTENSION = "NO_MIME_EXTENSION";
   String NO_MIME_TYPE = "NO_MIME_TYPE";
   String NO_PARAM_NAME = "NO_PARAM_NAME";
   String NO_PARAM_VALUE = "NO_PARAM_VALUE";
   String NO_SERVLET_NAME = "NO_SERVLET_NAME";
   String NO_SERVLET_DEF = "NO_SERVLET_DEF";
   String MULTIPLE_DEFINES_SERVLET_DEF = "MULTIPLE_DEFINES_SERVLET_DEF";
   String MULTIPLE_DEFINES_FILTER_MAPPING = "MULTIPLE_DEFINES_FILTER_MAPPING";
   String NO_MAPPING_SERVLET_NAME = "NO_MAPPING_SERVLET_NAME";
   String NO_URL_PATTERN = "NO_URL_PATTERN";
   String INVALID_SESSION_TIMEOUT = "INVALID_SESSION_TIMEOUT";
   String NO_TAGLIB_URI = "NO_TAGLIB_URI";
   String NO_TAGLIB_LOCATION = "NO_TAGLIB_LOCATION";
   String NO_WEB_RESOURCE = "NO_WEB_RESOURCE";
   String NO_LISTENER_CLASS = "NO_LISTENER_CLASS";
   String NO_FILTER_NAME = "NO_FILTER_NAME";
   String NO_FILTER_CLASS = "NO_FILTER_CLASS";
   String NO_FILTER_MAPPING_DEF = "NO_FILTER_MAPPING_DEF";
   String NO_URL_MATCH_MAP_CLASS = "NO_URL_MATCH_MAP_CLASS";
   String NO_PREPROCESSOR_NAME = "NO_PREPROCESSOR_NAME";
   String NO_PREPROCESSOR_URL_PATTERN = "NO_PREPROCESSOR_URL_PATTERN";
   String NO_MAPPING_PREPROCESSOR_NAME = "NO_MAPPING_PREPROCESSOR_NAME";
   String NO_PREPROCESSOR_CLASS = "NO_PREPROCESSOR_CLASS";
   String NO_RES_REF_NAME_SET = "NO_RES_REF_NAME_SET";
   String NO_RES_REF_TYPE_SET = "NO_RES_REF_TYPE_SET";
   String INVALID_RES_TYPE = "INVALID_RES_TYPE";
   String NO_RES_AUTH_SET = "NO_RES_AUTH_SET";
   String INVALID_RES_AUTH = "INVALID_RES_AUTH";
   String NO_RES_JNDI_NAME = "NO_RES_JNDI_NAME";
   String INVALID_RES_JNDI_NAME = "INVALID_RES_JNDI_NAME";
   String NO_ENV_ENTRY_VALUE_SET = "NO_ENV_ENTRY_VALUE_SET";
   String NO_ENV_ENTRY_NAME_SET = "NO_ENV_ENTRY_NAME_SET";
   String INVALID_ENV_TYPE = "INVALID_ENV_TYPE";
   String ENV_VALUE_NOT_OF_TYPE = "ENV_VALUE_NOT_OF_TYPE";
   String NO_EJB_REF_TYPE_SET = "NO_EJB_REF_TYPE_SET";
   String INVALID_EJB_REF_TYPE = "INVALID_EJB_REF_TYPE";
   String NO_EJB_REF_HOME_SET = "NO_EJB_REF_HOME_SET";
   String NO_EJB_REF_REMOTE_SET = "NO_EJB_REF_REMOTE_SET";
   String NO_EJB_REF_JNDI_NAME_SET = "NO_EJB_REF_JNDI_NAME_SET";
   String NO_ROLE_NAME_SET = "NO_ROLE_NAME_SET";
   String NO_SECURITY_ROLE_NAME_SET = "NO_SECURITY_ROLE_NAME_SET";
   String NO_SECURITY_ROLE_LINK_SET = "NO_SECURITY_ROLE_LINK_SET";

   void toXML(XMLWriter var1);
}
