package com.oracle.weblogic.lifecycle;

public enum LifecycleOperationType {
   CREATE_RUNTIME,
   DELETE_RUNTIME,
   UPDATE_RUNTIME,
   SCALE_UP_RUNTIME,
   SCALE_DOWN_RUNTIME,
   CREATE_PARTITION,
   DELETE_PARTITION,
   UPDATE_PARTITION,
   MIGRATE_PARTITION,
   QUIESCE_RUNTIME,
   START_RUNTIME,
   START_PARTITION,
   QUIESCE_PARTITION,
   RESTART_PARTITION;
}
