package weblogic.diagnostics.instrumentation.engine.base;

import org.objectweb.asm.Opcodes;
import weblogic.diagnostics.instrumentation.DiagnosticAction;
import weblogic.diagnostics.instrumentation.DiagnosticActionState;
import weblogic.diagnostics.instrumentation.DiagnosticMonitor;
import weblogic.diagnostics.instrumentation.DynamicJoinPoint;
import weblogic.diagnostics.instrumentation.JoinPoint;
import weblogic.diagnostics.instrumentation.LocalHolder;
import weblogic.diagnostics.instrumentation.MonitorLocalHolder;
import weblogic.diagnostics.instrumentation.PointcutHandlingInfo;
import weblogic.diagnostics.instrumentation.ValueHandlingInfo;

public interface InstrumentationEngineConstants extends Opcodes {
   String DEFAULT_PREFIX = "_WLDF$INST_";
   String VERSION_FIELD_NAME = "_WLDF$INST_VERSION";
   String VERSION_FIELD_VALUE = "9.0.0";
   String JOINPOINT_PREFIX = "_WLDF$INST_JPFLD_";
   String FIELD_PREFIX = "_WLDF$INST_FLD_";
   String CLASS_FIELD_NAME = "_WLDF$INST_FLD_class";
   String METHOD_EXEC_PREFIX = "_WLDF$INST_EXEC_";
   String METHOD_CALL_PREFIX = "_WLDF$INST_CALL_";
   String AUX_CLASSNAME_PREFIX = "_WLDF$INST_AUX_CLASS_";
   String PACKAGE_SEPARATOR = "/";
   String ENGINE_CONFIGURATION_FILE = "weblogic/diagnostics/instrumentation/engine/InstrumentationEngineConfig.xml";
   String SERIALIZED_ENGINE_CONFIGURATION_RESOURCE = "weblogic/diagnostics/instrumentation/engine/InstrumentationEngineConfig.ser";
   String SERIALIZED_ENGINE_CONFIGURATION_FILE = "InstrumentationEngineConfig.ser";
   String ROOT_CONFIG_NAME = "Builtin";
   String PREFIX_SEPARATOR = "/";
   String STATELESS_ACTIONS_GROUP = "StatelessActions";
   String AROUND_ACTIONS_GROUP = "AroundActions";
   String DATAGATHERING_STATELESS_ACTIONS_GROUP = "DataGatheringStatelessActions";
   String DATAGATHERING_AROUND_ACTIONS_GROUP = "DataGatheringAroundActions";
   int EXECUTION_POINTCUT = 0;
   int CALL_POINTCUT = 1;
   int WITHIN_POINTCUT = 2;
   int CONSTRUCTION_POINTCUT = 3;
   int NEWCALL_POINTCUT = 4;
   int CATCH_POINTCUT = 5;
   int ADVICE_LOCATION_BEFORE = 1;
   int ADVICE_LOCATION_AFTER = 2;
   int ADVICE_LOCATION_AROUND = 3;
   String SUID_NAME = "serialVersionUID";
   String INITIALIZER_NAME = "<init>";
   String INITIALIZER_DESC = "()V";
   String STATIC_INITIALIZER_NAME = "<clinit>";
   int WRAPPER_CODEGEN_POLICY = 1;
   int INLINED_CODEGEN_POLICY = 2;
   int JVM_CLASSFILE_MAGIC = -889275714;
   int MAX_METHOD_SIZE = 65536;
   int CP_CONSTANT_CLASS = 7;
   int CP_CONSTANT_FIELDREF = 9;
   int CP_CONSTANT_METHODREF = 10;
   int CP_CONSTANT_INTERFACEMETHODREF = 11;
   int CP_CONSTANT_STRING = 8;
   int CP_CONSTANT_INTEGER = 3;
   int CP_CONSTANT_FLOAT = 4;
   int CP_CONSTANT_LONG = 5;
   int CP_CONSTANT_DOUBLE = 6;
   int CP_CONSTANT_NAMEANDTYPE = 12;
   int CP_CONSTANT_UTF8 = 1;
   int CP_CONSTANT_METHODHANDLE = 15;
   int CP_CONSTANT_METHODTYPE = 16;
   int CP_CONSTANT_INVOKEDYNAMIC = 18;
   String WLDF_INST_PACKAGENAME = "weblogic/diagnostics/instrumentation";
   String WLDF_DEFAULT_SUPPORTCLASSNAME = "weblogic/diagnostics/instrumentation/InstrumentationSupport";
   String WLDF_ENGINE_PACKAGENAME = "weblogic/diagnostics/instrumentation/engine";
   String WLDF_DIAGMON_CLASSNAME = DiagnosticMonitor.class.getName().replace('.', '/');
   String WLDF_STDMON_CLASSNAME = "weblogic/diagnostics/instrumentation/StandardMonitor";
   String WLDF_DELMON_CLASSNAME = "weblogic/diagnostics/instrumentation/DelegatingMonitor";
   String WLDF_ACTION_CLASSNAME = "weblogic/diagnostics/instrumentation/DiagnosticAction";
   String WLDF_STATELESS_ACTION_CLASSNAME = "weblogic/diagnostics/instrumentation/StatelessDiagnosticAction";
   String WLDF_AROUND_ACTION_CLASSNAME = "weblogic/diagnostics/instrumentation/AroundDiagnosticAction";
   String WLDF_ACTIONSTATE_CLASSNAME = "weblogic/diagnostics/instrumentation/DiagnosticActionState";
   String WLDF_JOINPOINT_CLASSNAME = "weblogic/diagnostics/instrumentation/JoinPoint";
   String WLDF_DYNAMIC_JOINPOINT_CLASSNAME = "weblogic/diagnostics/instrumentation/DynamicJoinPoint";
   String WLDF_JOINPOINT_CONSTRUCTOR_DESC = "(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V";
   String WLDF_CREATE_JOINPOINT_DESC = "(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;Z)L" + JoinPoint.class.getName().replace('.', '/') + ";";
   String WLDF_VALUEHANDLINGINFO_CLASSNAME = "weblogic/diagnostics/instrumentation/ValueHandlingInfo";
   String WLDF_VALUEHANDLINGINFO_CREATE_DESC = "(Ljava/lang/String;Ljava/lang/String;ZZ)L" + ValueHandlingInfo.class.getName().replace('.', '/') + ";";
   String WLDF_INSTRUMENTATIONSUPPORT_MAKEMAP_NAME = "makeMap";
   String WLDF_POINTCUTHANDLINGINFO_CLASSNAME = "weblogic/diagnostics/instrumentation/PointcutHandlingInfo";
   String WLDF_POINTCUTHANDLINGINFO_CREATE_DESC = "(L" + ValueHandlingInfo.class.getName().replace('.', '/') + ";L" + ValueHandlingInfo.class.getName().replace('.', '/') + ";[L" + ValueHandlingInfo.class.getName().replace('.', '/') + ";)L" + PointcutHandlingInfo.class.getName().replace('.', '/') + ";";
   String WLDF_INSTRUMENTATIONSUPPORT_MAKEMAP_DESC = "([Ljava/lang/String;[L" + PointcutHandlingInfo.class.getName().replace('.', '/') + ";)Ljava/util/Map;";
   String WLDF_DYNAMIC_JOINPOINT_CONSTRUCTOR_DESC = "(L" + JoinPoint.class.getName().replace('.', '/') + ";[Ljava/lang/Object;Ljava/lang/Object;)V";
   String WLDF_CREATE_DYNAMIC_JOINPOINT_DESC = "(L" + JoinPoint.class.getName().replace('.', '/') + ";[Ljava/lang/Object;Ljava/lang/Object;)L" + DynamicJoinPoint.class.getName().replace('.', '/') + ";";
   String WLDF_CREATE_DYNAMIC_JOINPOINT_HOLDER_DESC = "(L" + LocalHolder.class.getName().replace('.', '/') + ";)V";
   String WLDF_DIAGNOSTICMONITOR_CLASSNAME = DiagnosticMonitor.class.getName().replace('.', '/');
   String WLDF_LOCALHOLDER_CLASSNAME = "weblogic/diagnostics/instrumentation/LocalHolder";
   String WLDF_LOCALHOLDER_JOINPOINT_FIELDNAME = "jp";
   String WLDF_LOCALHOLDER_ARGUMENTS_FIELDNAME = "args";
   String WLDF_LOCALHOLDER_THISARG_FIELDNAME = "thisArg";
   String WLDF_LOCALHOLDER_ARGSCAPTURE_FIELDNAME = "argsCapture";
   String WLDF_LOCALHOLDER_MONITORINDEX_FIELDNAME = "monitorIndex";
   String WLDF_LOCALHOLDER_MONITORHOLDER_FIELDNAME = "monitorHolder";
   String WLDF_LOCALHOLDER_THROWABLE_FIELDNAME = "th";
   String WLDF_LOCALHOLDER_RETURN_FIELDNAME = "ret";
   String WLDF_LOCALHOLDER_JOINPOINT_TYPE = "L" + JoinPoint.class.getName().replace('.', '/') + ";";
   String WLDF_LOCALHOLDER_ARGUMENTS_TYPE = "[Ljava/lang/Object;";
   String WLDF_LOCALHOLDER_THISARG_TYPE = "Ljava/lang/Object;";
   String WLDF_LOCALHOLDER_ARGSCAPTURE_TYPE = "Z";
   String WLDF_LOCALHOLDER_MONITORINDEX_TYPE = "I";
   String WLDF_LOCALHOLDER_MONITORHOLDER_TYPE = "[L" + MonitorLocalHolder.class.getName().replace('.', '/') + ";";
   String WLDF_LOCALHOLDER_THROWABLE_TYPE = "Ljava/lang/Throwable;";
   String WLDF_LOCALHOLDER_RETURN_TYPE = "Ljava/lang/Object;";
   String WLDF_LOCALHOLDER_GETINSTANCE_DESC = "(L" + JoinPoint.class.getName().replace('.', '/') + ";[L" + DiagnosticMonitor.class.getName().replace('.', '/') + ";)L" + LocalHolder.class.getName().replace('.', '/') + ";";
   String WLDF_LOCALHOLDER_GETINSTANCE_DESC_AUXKEY = "(II)L" + LocalHolder.class.getName().replace('.', '/') + ";";
   String WLDF_LOCALHOLDER_GETINSTANCE_NAME = "getInstance";
   String WLDF_LOCALHOLDER_RESETPOSTBEGIN_NAME = "resetPostBegin";
   String WLDF_LOCALHOLDER_RESETPOSTBEGIN_DESC = "()V";
   String WLDF_GETACTIONS_DESC = "()[L" + DiagnosticAction.class.getName().replace('.', '/') + ";";
   String WLDF_SUPPORT_GETMONITOR_DESC = "(Ljava/lang/Class;Ljava/lang/String;)L" + DiagnosticMonitor.class.getName().replace('.', '/') + ";";
   String WLDF_SUPPORT_GETACTIONSTATES_DESC = "([L" + DiagnosticAction.class.getName().replace('.', '/') + ";)[L" + DiagnosticActionState.class.getName().replace('.', '/') + ";";
   String WLDF_SUPPORT_APPLYACTIONSTATESHOLDER_DESC = "(L" + LocalHolder.class.getName().replace('.', '/') + ";)V";
   String WLDF_SUPPORT_PROCESS_HOLDER_DESC = "(L" + LocalHolder.class.getName().replace('.', '/') + ";)V";
   String WLDF_SUPPORT_PROCESS_DESC = "(L" + JoinPoint.class.getName().replace('.', '/') + ";L" + DiagnosticMonitor.class.getName().replace('.', '/') + ";[L" + DiagnosticAction.class.getName().replace('.', '/') + ";)V";
   String WLDF_SUPPORT_PROCESS_EXC_DESC = "(L" + JoinPoint.class.getName().replace('.', '/') + ";L" + DiagnosticMonitor.class.getName().replace('.', '/') + ";[L" + DiagnosticAction.class.getName().replace('.', '/') + ";Ljava/lang/Throwable;)V";
   String WLDF_SUPPORT_PREPROCESS_HOLDER_DESC = "(L" + LocalHolder.class.getName().replace('.', '/') + ";)V";
   String WLDF_SUPPORT_PREPROCESS_DESC = "(L" + JoinPoint.class.getName().replace('.', '/') + ";L" + DiagnosticMonitor.class.getName().replace('.', '/') + ";[L" + DiagnosticAction.class.getName().replace('.', '/') + ";[L" + DiagnosticActionState.class.getName().replace('.', '/') + ";)V";
   String WLDF_SUPPORT_POSTPROCESS_HOLDER_DESC = "(L" + LocalHolder.class.getName().replace('.', '/') + ";)V";
   String WLDF_SUPPORT_POSTPROCESS_DESC = "(L" + JoinPoint.class.getName().replace('.', '/') + ";L" + DiagnosticMonitor.class.getName().replace('.', '/') + ";[L" + DiagnosticAction.class.getName().replace('.', '/') + ";[L" + DiagnosticActionState.class.getName().replace('.', '/') + ";)V";
   String WLDF_SUPPORT_POSTPROCESS_EXC_DESC = "(L" + JoinPoint.class.getName().replace('.', '/') + ";L" + DiagnosticMonitor.class.getName().replace('.', '/') + ";[L" + DiagnosticAction.class.getName().replace('.', '/') + ";[L" + DiagnosticActionState.class.getName().replace('.', '/') + ";Ljava/lang/Throwable;)V";
   String WLDF_SUPPORT_CATCH_THROWABLE_DESC = "(Ljava/lang/Throwable;)V";
   String WLDF_SUPPORT_CONVERT_TO_BOOLEAN_DESC = "(Z)Ljava/lang/Object;";
   String WLDF_SUPPORT_CONVERT_TO_CHAR_DESC = "(C)Ljava/lang/Object;";
   String WLDF_SUPPORT_CONVERT_TO_BYTE_DESC = "(B)Ljava/lang/Object;";
   String WLDF_SUPPORT_CONVERT_TO_SHORT_DESC = "(S)Ljava/lang/Object;";
   String WLDF_SUPPORT_CONVERT_TO_INT_DESC = "(I)Ljava/lang/Object;";
   String WLDF_SUPPORT_CONVERT_TO_FLOAT_DESC = "(F)Ljava/lang/Object;";
   String WLDF_SUPPORT_CONVERT_TO_LONG_DESC = "(J)Ljava/lang/Object;";
   String WLDF_SUPPORT_CONVERT_TO_DOUBLE_DESC = "(D)Ljava/lang/Object;";
   String WLDF_SUPPORT_CONVERT_FROM_BOOLEAN_DESC = "(Ljava/lang/Boolean;)Z";
   String WLDF_SUPPORT_CONVERT_FROM_CHAR_DESC = "(Ljava/lang/Character;)C";
   String WLDF_SUPPORT_CONVERT_FROM_BYTE_DESC = "(Ljava/lang/Byte;)B";
   String WLDF_SUPPORT_CONVERT_FROM_SHORT_DESC = "(Ljava/lang/Short;)S";
   String WLDF_SUPPORT_CONVERT_FROM_INT_DESC = "(Ljava/lang/Integer;)I";
   String WLDF_SUPPORT_CONVERT_FROM_FLOAT_DESC = "(Ljava/lang/Float;)F";
   String WLDF_SUPPORT_CONVERT_FROM_LONG_DESC = "(Ljava/lang/Long;)J";
   String WLDF_SUPPORT_CONVERT_FROM_DOUBLE_DESC = "(Ljava/lang/Double;)D";
}
